(()=>{
  document.querySelectorAll('img[data-fallback]').forEach(img=>img.addEventListener('error',()=>{if(img.src!==img.dataset.fallback)img.src=img.dataset.fallback;}));
  const chosen=new Set();
  document.querySelectorAll('#sourceTypes .source-card').forEach(card=>card.addEventListener('click',()=>{const k=card.dataset.key;chosen.has(k)?chosen.delete(k):chosen.add(k);card.classList.toggle('selected',chosen.has(k));}));
  document.getElementById('checkSources').addEventListener('click',()=>{const strong=['osm','sat','field'];const ok=strong.every(x=>chosen.has(x))&&!chosen.has('post');document.getElementById('sourceFb').innerHTML=ok?'<span class="ok">Сильний набір.</span> Онлайн-карта дає актуальну картографічну версію, знімок — незалежний просторовий доказ, польова перевірка — стан на місці. Стару карту можна додати для історичного порівняння.':'<span class="bad">Набір ще слабкий.</span> Для «зниклої дороги» потрібні щонайменше онлайн-карта + незалежний просторовий доказ + перевірка. Один допис без паспорта не замінює доказ.';});
  document.querySelectorAll('#relLab .rel-card').forEach(card=>{card.querySelectorAll('.stars button').forEach(btn=>btn.addEventListener('click',()=>{card.dataset.pick=btn.dataset.v;card.querySelectorAll('.stars button').forEach(b=>b.classList.toggle('active',b===btn));card.querySelector('.meter span').style.width=(Number(btn.dataset.v)/3*100)+'%';}));});
  document.getElementById('checkReliability').addEventListener('click',()=>{let done=0,correct=0;document.querySelectorAll('#relLab .rel-card').forEach(c=>{if(c.dataset.pick){done++;if(c.dataset.pick===c.dataset.ideal)correct++;}});document.getElementById('relFb').innerHTML=done<3?'<span class="bad">Оцініть усі три джерела.</span>':correct===3?'<span class="ok">3/3.</span> Ви врахували походження, дату й придатність джерела.':'<b>'+correct+'/3.</b> А: 3★ — є установа, дата й легенда. Б: 1★ — бракує паспорта. В: 2★ — надійне для багатьох завдань, але не обов’язково актуальне для швидких змін.';});
  document.getElementById('buildPlan').addEventListener('click',()=>{const q=document.getElementById('obsQ').value,p=document.getElementById('obsPlace').value,f=document.getElementById('obsFreq').value,r=document.getElementById('obsRecord').value;const box=document.getElementById('planBox');if(!q||!p||!f||!r){box.innerHTML='<h3>Не вистачає параметрів</h3><p class="bad">Оберіть усі чотири елементи.</p>';return;}const strong=(p!=='Щодня випадкове місце'&&f!=='Один раз'&&r==='Число + одиниця + час + умови');box.innerHTML='<h3>'+(strong?'✅ Відтворюваний план':'⚠️ План потребує покращення')+'</h3><div class="plan-step"><span class="num">1</span><div><b>Питання:</b> '+q+'</div></div><div class="plan-step"><span class="num">2</span><div><b>Місце:</b> '+p+'</div></div><div class="plan-step"><span class="num">3</span><div><b>Повторення:</b> '+f+'</div></div><div class="plan-step"><span class="num">4</span><div><b>Запис:</b> '+r+'</div></div><p>'+(strong?'Інший учень зможе повторити дослідження й порівняти результати.':'Стабілізуйте місце, додайте повторення й числовий запис із одиницею та умовами.')+'</p>';});
  const temps=[18,20,19,25,23,21,20],days=['Пн','Вт','Ср','Чт','Пт','Сб','Нд'];const bars=document.getElementById('bars');temps.forEach((t,i)=>{const w=document.createElement('div');w.className='bar-wrap';w.innerHTML='<div class="bar" style="height:'+(t*6)+'px"><b>'+t+'°</b></div>'+days[i];bars.appendChild(w);});
  const dataText={one:'Один день показує лише один стан. Він не доводить типовість або закономірність.',series:'Так. Ряд повторних спостережень показує коливання й дозволяє порівнювати дні. Але причина стрибка у четвер потребує додаткових даних.',mean:'Середнє корисне, але приховує коливання: 25 °C у четвер майже зникає з поля зору.'};document.querySelectorAll('.decision-row button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.decision-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('dataFb').textContent=dataText[b.dataset.claim];}));
  let express=0;document.querySelectorAll('#expressGrid .q button').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.closest('.q');if(q.dataset.done)return;q.dataset.done='1';const ok=btn.dataset.a===q.dataset.correct;q.dataset.state=ok?'ok':'bad';if(ok)express++;document.getElementById('expressFb').innerHTML='Результат: <b>'+express+' / 5</b>'+(document.querySelectorAll('#expressGrid .q[data-done="1"]').length===5?(express>=4?' • <span class="ok">готові до теорії</span>':' • перегляньте критерії надійності'):'');}));
  function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
  document.getElementById('compareHyp').addEventListener('click',()=>{const h=document.getElementById('hyp').value.trim(),c=document.getElementById('cerC').value.trim(),e=document.getElementById('cerE').value.trim(),r=document.getElementById('cerR').value.trim(),box=document.getElementById('compareBox');box.classList.remove('hidden');box.innerHTML=(!h||!c||!e||!r)?'<span class="bad">Заповніть гіпотезу та всі три частини CER.</span>':'<b>Було:</b> '+esc(h)+'<br><br><b>Стало:</b> '+esc(c)+'<br><b>Доказ:</b> '+esc(e)+'<br><b>Пояснення:</b> '+esc(r)+'<br><br><span class="ok">Перевірка:</span> чи назвали ви не лише джерело, а й критерій його надійності та межу висновку?';});
  function validName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґA-Za-z'’\-]+$/.test(x));}
  const gate=document.getElementById('quizGate'),quiz=document.getElementById('quiz'),fn=document.getElementById('fullName'),cl=document.getElementById('studentClass');const m1=document.getElementById('m1'),m2=document.getElementById('m2'),m3=document.getElementById('m3');document.getElementById('startQuiz').addEventListener('click',()=>{if(!validName(fn.value)||!cl.value){document.getElementById('gateError').textContent='Введіть ім’я, прізвище та оберіть клас.';return;}document.getElementById('gateError').textContent='';gate.classList.add('hidden');quiz.classList.remove('hidden');document.getElementById('shuffleOrder').click();quiz.scrollIntoView({behavior:'smooth',block:'start'});});
  function move(row,d){const p=row.parentElement;if(d<0&&row.previousElementSibling)p.insertBefore(row,row.previousElementSibling);if(d>0&&row.nextElementSibling)p.insertBefore(row.nextElementSibling,row);}document.getElementById('orderList').addEventListener('click',e=>{const row=e.target.closest('.order-row');if(!row)return;if(e.target.classList.contains('up'))move(row,-1);if(e.target.classList.contains('down'))move(row,1);});document.getElementById('shuffleOrder').addEventListener('click',()=>{const p=document.getElementById('orderList'),rows=[...p.children];rows.sort(()=>Math.random()-.5).forEach(r=>p.appendChild(r));});
  const radio=n=>{const e=document.querySelector('input[name="'+n+'"]:checked');return e?e.value:null};const checks=n=>[...document.querySelectorAll('input[name="'+n+'"]:checked')].map(x=>x.value).sort();const same=(a,b)=>a.length===b.length&&a.every((x,i)=>x===b[i]);
  quiz.addEventListener('submit',e=>{e.preventDefault();let complete=true;['q1','q2','q3','q4','q9','q10'].forEach(n=>{if(!radio(n))complete=false});if(!checks('q5').length||!checks('q6').length)complete=false;if(!m1.value||!m2.value||!m3.value)complete=false;if(!complete){document.getElementById('quizMsg').innerHTML='<span class="bad">Є незаповнені завдання.</span> Перевірте всі 10 пунктів.';return;}let s=0;if(radio('q1')==='b')s++;if(radio('q2')==='a')s++;if(radio('q3')==='b')s++;if(radio('q4')==='b')s++;if(same(checks('q5'),['atlas','ency','map']))s++;if(same(checks('q6'),['date','field','third']))s++;if(m1.value==='a'&&m2.value==='b'&&m3.value==='c')s++;const o=[...document.querySelectorAll('#orderList .order-row')].map(x=>x.dataset.key);if(JSON.stringify(o)===JSON.stringify(['question','method','observe','conclusion']))s++;if(radio('q9')==='b')s++;if(radio('q10')==='c')s++;const comment=s<=4?'Повторіть критерії надійності джерел і алгоритм спостереження.':s<=7?'Достатній результат. Зверніть увагу на актуальність, відтворюваність і межі висновку.':s<=9?'Добре. Ви впевнено добираєте джерела й перевіряєте докази.':'Відмінно. Ви оцінюєте джерела, плануєте спостереження й бачите межі даних.';const card=document.getElementById('resultCard');card.innerHTML='<h3>Картка результату</h3><div><b>'+esc(fn.value.trim())+'</b> • '+esc(cl.value)+'</div><div class="small">Тема: Джерела географічної інформації та власні спостереження</div><div class="score">'+s+' / 10</div><div><b>'+s*10+'%</b></div><p>'+comment+'</p><p class="small">Дата й час: '+new Date().toLocaleString('uk-UA')+'</p><div class="notice"><b>Зробіть скриншот цієї картки та надішліть учителю.</b></div><button type="button" class="secondary" onclick="window.print()" style="margin-top:9px">Друк / зберегти PDF</button>';card.classList.remove('hidden');document.getElementById('quizMsg').innerHTML='<span class="ok">Тест завершено.</span> Результат сформовано нижче.';card.scrollIntoView({behavior:'smooth',block:'center'});});
})();
