const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const names={energy:'A — температура й амплітуда',pressure:'B — тиск і вітер',water:'C — вологість та опади',climate:'D — погода й клімат',hazard:'E — небезпечні явища',evidence:'F — доказ і CER'};
routeOut.insertAdjacentHTML('afterend','<img class="route-diagram" src="assets/correction-route.svg" alt="Схема маршруту корекції: помилка, діагностика, станція, нова спроба, повторна перевірка">');
routeBtn.onclick=()=>{const picked=$$('.weak:checked').map(x=>x.value);$$('.station').forEach(s=>s.classList.remove('recommended'));if(!picked.length){routeOut.textContent='Оберіть хоча б одне слабке місце.';return}picked.forEach(v=>document.querySelector(`[data-station="${v}"]`)?.classList.add('recommended'));routeOut.innerHTML=`Ваш маршрут: <b>${picked.map(v=>names[v]).join(' → ')}</b>. Почніть із першої підсвіченої станції; решту проходьте лише за потреби.`;document.querySelector(`[data-station="${picked[0]}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})};
$$('[data-check]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.check;if(k==='amp'){ampFb.textContent=Number(ampAns.value)===13?'✓ 13°C. Алгоритм відновлено.':'Ще раз: амплітуда = Tmax − Tmin.'}if(k==='rain'){rainFb.textContent=Number(rainAns.value)===12?'✓ 12 мм = 12 л/м².':'1 мм на 1 м² відповідає 1 літру води.'}if(k==='humidity'){humidityFb.textContent=humidity.value==='no'?'✓ Висока RH не гарантує опади.':'Ні: висока вологість — лише одна з умов.'}if(k==='proof'){const t=proofText.value.toLowerCase();const hasNums=(t.includes('1018')||t.includes('1004'))&&(t.includes('30')||t.includes('85')||t.includes('2')||t.includes('9'));const avoids=!t.includes('гарант');proofFb.textContent=t.length>80&&hasNums&&avoids?'✓ Є теза/висновок, числові докази й обережне причинне пояснення.':'Сильна відповідь має містити щонайменше два числові докази та не робити 100% прогнозу.'}}));
$$('[data-group="wind"] button').forEach(b=>b.onclick=()=>{const ok=b.dataset.v==='ab';$$('[data-group="wind"] button').forEach(x=>x.classList.remove('good','bad'));b.classList.add(ok?'good':'bad');windFb.textContent=ok?'✓ Від вищого тиску до нижчого — базова модель правильна.':'Перевірте числа: 1024 гПа > 998 гПа.'});
$$('[data-group="storm"] button').forEach(b=>b.onclick=()=>{const ok=b.dataset.v==='safe';$$('[data-group="storm"] button').forEach(x=>x.classList.remove('good','bad'));b.classList.add(ok?'good':'bad');stormFb.textContent=ok?'✓ Капітальна будівля або закритий автомобіль — значно безпечніший вибір.':'Окреме високе дерево й відкрита височина під час грози небезпечні.'});
$$('[data-climate]').forEach(b=>b.onclick=()=>{const ok=b.dataset.climate==='yes';$$('[data-climate]').forEach(x=>x.classList.remove('good','bad'));b.classList.add(ok?'good':'bad');climateFb.textContent=ok?'✓ Клімат описують багаторічні статистичні характеристики.':'Один день або кілька днів описують погоду, а не клімат.'});
const quizData=[
['У місті Tmin = −2°C, Tmax = +11°C. Добова амплітуда?',['9°C','13°C','11°C'],1],
['Яка ситуація найкраще відповідає руху повітря за різницею тиску?',['від 1028 гПа до 1002 гПа','від 1002 гПа до 1028 гПа','тиск не пов’язаний з вітром'],0],
['20 мм опадів на 1 м² — це…',['2 л','20 л','200 л'],1],
['Що саме описує відносна вологість?',['частку водяної пари від максимально можливої за цієї температури','кількість опадів за добу','швидкість вітру'],0],
['Який набір даних доречніший для характеристики клімату?',['один спекотний день','30-річні сезонні середні','прогноз на завтра'],1],
['Тиск падає, вітер посилюється, хмарність зростає. Який висновок коректніший?',['дощ гарантований','зростає ймовірність нестійкої погоди','клімат змінився'],1],
['Яке рішення безпечніше під час грози?',['стати під окремим високим деревом','сховатися в капітальній будівлі','залишитися на відкритій височині'],1],
['Чому один супутниковий кадр із ясним небом не доводить сухий клімат?',['бо супутники не бачать хмар','бо клімат потребує довгого ряду спостережень','бо клімат не пов’язаний з опадами'],1],
['Яке твердження про хмарність коректне?',['100% хмарності завжди означає сильний дощ','хмарність і опади — різні характеристики','за хмарністю не можна нічого дізнатися'],1],
['Який висновок є доказовим?',['Мені здається, буде дощ','Тиск упав на 14 гПа, хмарність зросла до 90%, вітер посилився — імовірність нестійкої погоди зросла','Якщо тиск падає, дощ завжди гарантований'],1]
];
const quizForm=document.getElementById('quiz');
function renderQuiz(){questions.innerHTML=quizData.map((q,i)=>`<div class="q"><b>${i+1}. ${q[0]}</b>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('')}
renderQuiz();
unlock.onclick=()=>{if(!surname.value.trim()||!name.value.trim()||!klass.value.trim()){gateMsg.textContent='Заповніть прізвище, ім’я та клас.';return}gateMsg.textContent='Дані прийнято. Під час повторної перевірки не відкривайте пояснення корекційних станцій.';quizForm.classList.remove('hidden');unlock.disabled=true;quizForm.scrollIntoView({behavior:'smooth'})};
quizForm.onsubmit=e=>{e.preventDefault();let p=0;quizData.forEach((q,i)=>{const a=document.querySelector(`input[name="q${i}"]:checked`);if(a&&Number(a.value)===q[2])p++});score.classList.remove('hidden');score.innerHTML=`${surname.value} ${name.value}, ${klass.value}: <b>${p}/10</b>. ${p>=8?'Корекція спрацювала: основні алгоритми відновлено.':p>=6?'Є прогрес, але варто повторити станції, де залишилися помилки.':'Поверніться до маршруту корекції й пройдіть 2–3 слабкі станції ще раз.'}`;score.scrollIntoView({behavior:'smooth'})};