
(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function fb(id,msg,ok){const e=$(id);e.textContent=msg;e.className='feedback show '+(ok?'good':'bad')}
$$('[data-start]').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const ok=b.dataset.start==='b';fb('#startFb',ok?'Так. Склянка — окреме тіло, а скло — матеріал, з якого її виготовлено.':'Спробуйте розрізнити назву предмета і назву того, з чого він зроблений.',ok)}));
$$('#photoBodyChoice button').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.v==='body';fb('#photoBodyFb',ok?'Так: відкривач — окремий предмет, тобто фізичне тіло.':'Ні. Речовини/матеріали тут — дерево, метал, пластик, гума.',ok)}));
function toggleGroup(sel){$$(sel+' button').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('selected')))}toggleGroup('#materials');toggleGroup('#videoProps');
$('#checkMaterials').addEventListener('click',()=>{const s=$$('#materials button.selected');const good=s.filter(x=>x.dataset.ok==='1').length,bad=s.filter(x=>x.dataset.ok==='0').length;fb('#materialsFb',good===4&&bad===0?'Усі матеріали вибрані правильно: деревина, метал, пластик і гума. Скляна банка на фото — окреме тіло.':'Потрібно вибрати чотири матеріали предмета й не додавати речовини, яких у його описі немає.',good===4&&bad===0)});
$('#checkVideoProps').addEventListener('click',()=>{const s=$$('#videoProps button.selected');const good=s.filter(x=>x.dataset.ok==='1').length,bad=s.filter(x=>x.dataset.ok==='0').length;fb('#videoPropsFb',good>=3&&bad===0?'Так. Форму, розмір, об’єм і масу використовують для характеристики тіл.':'Не плутайте вимірювані/спостережувані характеристики з особистими оцінками.',good>=3&&bad===0)});
const partText={wood:'Деревина утворює основну оболонку олівця: тверда, але достатньо легко обробляється.',graphite:'Графітовий стрижень залишає слід на папері. Це інший матеріал усередині того самого тіла.',metal:'Металева обойма утримує гумку. Метал обрано через міцність і здатність зберігати форму.',rubber:'Гума пружна й стирає графітовий слід. Властивість матеріалу визначає його функцію.'};$$('[data-part]').forEach(b=>b.addEventListener('click',()=>fb('#modelFb',partText[b.dataset.part],true)));
$$('[data-mission]').forEach(b=>b.addEventListener('click',()=>{$$('.missionPanel').forEach(x=>x.classList.remove('active'));$('#mission-'+b.dataset.mission).classList.add('active')}));
$$('#proofChoice button').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.ok==='1';fb('#proofFb',ok?'Так. Один колір чи блиск не гарантує матеріал; сильніший доказ — перевірка кількох властивостей.':'Це слабкий доказ: зовнішній вигляд або думка іншої людини може ввести в оману.',ok)}));
$$('[data-myth]').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.myth==='true';fb('#mythFb',ok?'Влучно. Однаковий колір не означає однакову речовину: пластик може бути «металевого» кольору, а скло — забарвленим.':'Це твердження правильне: складні предмети часто поєднують кілька матеріалів.',ok)}));
['claim','evidence','reasoning'].forEach(k=>{const e=$('#cer-'+k);e.value=localStorage.getItem('g5l7-'+k)||'';e.addEventListener('input',()=>localStorage.setItem('g5l7-'+k,e.value))});$('#checkCer').addEventListener('click',()=>{const ok=['claim','evidence','reasoning'].every(k=>$('#cer-'+k).value.trim().length>=18);fb('#cerFb',ok?'CER заповнено. Перевірте, чи доказ конкретний, а пояснення показує, як він підтримує твердження.':'У кожній частині потрібно повне речення: твердження, конкретний доказ і пояснення зв’язку.',ok)});
const questions=[
{q:'Учениця тримає скляну пляшку. Що тут є тілом?',o:['скло','пляшка','прозорість','твердість'],a:1},
{q:'Який ряд містить лише речовини/матеріали?',o:['стілець, олівець, банка','скло, вода, залізо','ложка, сталь, чашка','книга, папір, дерево'],a:1},
{q:'Олівець складається з деревини, графіту, металу й гуми. Який висновок правильний?',o:['тіло завжди складається лише з однієї речовини','одне тіло може містити кілька матеріалів','деревина є тілом, а олівець — речовиною','матеріал не впливає на властивості предмета'],a:1},
{q:'Що з переліченого є характеристикою тіла?',o:['форма','популярність','краса','настрій'],a:0},
{q:'Що НЕ можна надійно визначити лише з фотографії предмета?',o:['приблизну форму','колір поверхні','магнітні властивості','наявність ручки'],a:2},
{q:'Який доказ найсильніше підтвердить, що невідоме тіло виготовлено з певного матеріалу?',o:['воно схоже за кольором','друг упевнений','перевірено кілька характерних властивостей','воно красиво блищить'],a:2},
{q:'Установіть правильну пару.',o:['склянка — речовина; скло — тіло','ключ — тіло; сталь — матеріал','вода — тіло; крапля — речовина','олівець — речовина; деревина — тіло'],a:1},
{q:'Яка послідовність дослідження найкраща?',o:['висновок → спостереження → припущення','припущення → спостереження/перевірка → висновок','фото → готова відповідь → перевірка не потрібна','назва → колір → висновок без перевірки'],a:1},
{q:'Два предмети однакового сріблястого кольору. Чого бракує для висновку, що обидва металеві?',o:['нічого, колір достатній','даних про інші властивості або склад','назви власника','ціни предметів'],a:1},
{q:'Оберіть найкращий CER-висновок.',o:['Склянка — це скло, бо так говорять.','Склянка — тіло, бо має форму; скло — матеріал, з якого вона виготовлена, тому ці поняття описують різні речі.','Скло — тіло, бо воно прозоре.','Усі прозорі тіла зроблені зі скла.'],a:1}
];
function validName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(x))}
$('#startQuiz').addEventListener('click',()=>{if(!validName($('#fullName').value)||!$('#studentClass').value.trim()){fb('#gateFb','Введіть ім’я, прізвище та клас.',false);return}$('#gate').style.display='none';const q=$('#quiz');q.innerHTML=questions.map((x,i)=>'<div class="q"><b>'+(i+1)+'. '+x.q+'</b>'+x.o.map((o,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'"> '+o+'</label>').join('')+'</div>').join('')+'<button class="btn alt" type="submit">Завершити тест</button>';q.classList.add('open')});
$('#quiz').addEventListener('submit',e=>{e.preventDefault();let s=0;questions.forEach((x,i)=>{const a=$('input[name="q'+i+'"]:checked');if(a&&+a.value===x.a)s++});const pct=s*10;const comment=s<=4?'Повторіть різницю між тілом, речовиною і властивістю.':s<=7?'Основа є; ще раз пропрацюйте межі висновку за фото.':s<=9?'Добре: поняття й логіка доказів засвоєні.':'Відмінно: Ви розрізняєте тіло, матеріал, властивість і силу доказу.';$('#quizResult').innerHTML='<div class="resultCard"><h3>Картка результату</h3><p><b>'+$('#fullName').value+'</b> • '+$('#studentClass').value+'</p><p style="font-size:2rem;font-weight:950">'+s+'/10 • '+pct+'%</p><p>'+comment+'</p><p><b>Дата/час:</b> '+new Date().toLocaleString('uk-UA')+'</p><p>📸 Зробіть скриншот цієї картки та надішліть учителю.</p></div>';$('#quizResult').scrollIntoView({behavior:'smooth',block:'center'})});
})();