document.querySelectorAll('.choice').forEach(box=>{box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.v===box.dataset.answer;box.querySelector('.feedback').textContent=ok?'✅ Саме так. Твердження спирається на спостережувані ознаки.':'↩️ Спробуйте ще раз: оберіть висновок, який можна обґрунтувати без здогадки.';}));});

document.querySelectorAll('.weather-btn').forEach(b=>b.addEventListener('click',()=>document.querySelector('#weatherOut').textContent=b.dataset.w));
document.querySelectorAll('.reveal').forEach(b=>b.addEventListener('click',()=>{const a=b.nextElementSibling;a.style.display=a.style.display==='block'?'none':'block';}));

const temp=document.querySelector('#temp'),rh=document.querySelector('#rh'),height=document.querySelector('#height');
function cloudSim(){const t=+temp.value,r=+rh.value,h=+height.value;document.querySelector('#tV').textContent=t+'°C';document.querySelector('#rhV').textContent=r+'%';document.querySelector('#hV').textContent=h+' м';const dew=t-(100-r)/5;const lifted=t-h*.0065;const sat=lifted<=dew;const blob=document.querySelector('#cloudBlob');blob.style.opacity=sat?1:Math.max(.12,r/180);blob.style.bottom=(26+Math.min(h/40,100))+'px';document.querySelector('#simOut').textContent=`Орієнтовно: точка роси ≈ ${dew.toFixed(1)}°C; температура піднятого повітря ≈ ${lifted.toFixed(1)}°C. ${sat?'У моделі досягнуто насичення → конденсація можлива.':'Повітря ще не охололо до точки роси.'}`;}
[temp,rh,height].forEach(x=>x.addEventListener('input',cloudSim));cloudSim();

const cover=document.querySelector('#cover');function coverSim(){const v=+cover.value;document.querySelector('#coverV').textContent=v+'%';document.querySelector('#coverCloud').style.height=v+'%';let d=v<15?'майже ясно':v<40?'малохмарно':v<70?'мінлива/значна хмарність':v<95?'хмарно':'суцільна хмарність';document.querySelector('#coverOut').textContent=`Оцінка: ${d}. Це опис покриття неба, а не ймовірність опадів.`;}cover.addEventListener('input',coverSim);coverSim();

const fogT=document.querySelector('#fogT'),dew=document.querySelector('#dew');function fogSim(){const t=+fogT.value,d=+dew.value;document.querySelector('#fogTV').textContent=t+'°C';document.querySelector('#dewV').textContent=d+'°C';const delta=t-d,near=delta<=1;document.querySelector('#fogScene i').style.background=near?'rgba(245,249,250,.82)':`rgba(245,249,250,${Math.max(0,.5-delta*.06)})`;document.querySelector('#fogOut').textContent=near?'Температура біля точки роси: насичення й туман дуже ймовірні за сприятливих умов.':`До точки роси ще приблизно ${delta}°C: одного охолодження поки недостатньо.`;}[fogT,dew].forEach(x=>x.addEventListener('input',fogSim));fogSim();

document.querySelector('#saveCer').addEventListener('click',()=>{const vals=['claim','evidence','reasoning'].map(id=>document.getElementById(id).value.trim());document.querySelector('#cerOut').textContent=vals.every(v=>v.length>=25)?'✅ CER має всі три частини. Перевірте, чи докази справді підтримують твердження, а пояснення містить причинний механізм.':'Доповніть відповідь: кожна частина має містити змістовне речення, а Evidence — щонайменше два конкретні докази.';});

document.querySelector('#openTest').addEventListener('click',()=>{const s=document.querySelector('#surname').value.trim(),n=document.querySelector('#name').value.trim(),k=document.querySelector('#klass').value.trim();if(s.length<2||n.length<2||k.length<2){document.querySelector('#gateMsg').textContent='Заповніть прізвище, ім’я та клас.';return;}document.querySelector('#quiz').classList.remove('hidden');document.querySelector('#gateMsg').textContent=`Тест відкрито для: ${s} ${n}, ${k}.`;});

document.querySelector('#quiz').addEventListener('submit',e=>{e.preventDefault();const ans={q1:'b',q2:'a',q3:'b',q4:'b',q5:'a',q6:'a',q7:'a',q8:'a',q9:'a',q10:'a'};let score=0,miss=[];Object.entries(ans).forEach(([q,a],i)=>{const x=document.querySelector(`input[name="${q}"]:checked`);if(x&&x.value===a)score++;else miss.push(i+1);});document.querySelector('#score').innerHTML=`Результат: <b>${score}/10</b>. ${miss.length?`Перевірте завдання: ${miss.join(', ')}.`:'Усі відповіді правильні.'}`;});