const pfName=document.getElementById('pfName'),pfSkill=document.getElementById('pfSkill'),pfProof=document.getElementById('pfProof'),pfNext=document.getElementById('pfNext'),pvName=document.getElementById('pvName'),pvSkill=document.getElementById('pvSkill'),pvProof=document.getElementById('pvProof'),pvNext=document.getElementById('pvNext'),routeCount=document.getElementById('routeCount'),routeProgress=document.getElementById('routeProgress'),routeOutput=document.getElementById('routeOutput'),goalText=document.getElementById('goalText'),goalDate=document.getElementById('goalDate'),timer=document.getElementById('timer'),timerText=document.getElementById('timerText'),gate=document.getElementById('gate'),gateErr=document.getElementById('gateErr'),quiz=document.getElementById('quiz'),result=document.getElementById('result'),fullName=document.getElementById('fullName'),studentClass=document.getElementById('studentClass');
const artifacts=[...document.querySelectorAll('.artifact')];artifacts.forEach(x=>x.addEventListener('click',()=>{x.classList.toggle('selected');document.querySelector('#artifactCount b').textContent=document.querySelectorAll('.artifact.selected').length}));
function checkArtifacts(){let correct=0;artifacts.forEach(x=>{x.classList.remove('wrong');const picked=x.classList.contains('selected');const good=x.dataset.good==='1';if(picked===good)correct++;else x.classList.add('wrong')});document.getElementById('artifactFb').textContent=correct===artifacts.length?'Точно. Портфоліо — це докази, а не склад файлів «про всяк випадок».':`Збігів ${correct}/${artifacts.length}. Подумайте: чи показує картка навичку, досвід, результат або прогрес?`}
function fillDemo(){pfName.value='Олексій, 8-Б';pfSkill.value='Умію структуровано пояснювати складну інформацію';pfProof.value='У командному проєкті створив схему і пояснив її класу; команда використала її у фінальній презентації';pfNext.value='Зробити 2 інфографіки на теми, які мені цікаві';updatePreview()}
function updatePreview(){pvName.textContent=pfName.value.trim()||'Ваше ім’я';pvSkill.textContent=pfSkill.value.trim()||'Тут з’явиться те, що у Вас уже виходить.';pvProof.textContent=pfProof.value.trim()||'Не «я креативний/а», а конкретний приклад.';pvNext.textContent=pfNext.value.trim()||'Що Ви хочете спробувати найближчим часом.'}
['pfName','pfSkill','pfProof','pfNext'].forEach(id=>document.getElementById(id).addEventListener('input',updatePreview));
const goalData=[['Хочу краще малювати',0],['До 20 жовтня намалюю 4 портретні етюди й порівняю перший із четвертим',1],['Хочу підтягнути англійську колись',0],['Протягом 30 днів вивчу 80 слів із теми подорожей і перевірю себе двома мінітестами',1],['Хочу стати успішним/успішною',0],['За 3 тижні змонтую одне відео до 60 секунд і попрошу двох людей дати конкретний відгук',1]];
const goalCases=document.getElementById('goalCases');goalData.forEach((g,i)=>{const d=document.createElement('div');d.className='goalcase';d.innerHTML=`<b>${g[0]}</b><div class="caseBtns"><button type="button" class="good" onclick="judgeGoal(${i},1,this)">Ціль</button><button type="button" class="badbtn" onclick="judgeGoal(${i},0,this)">Туман</button></div><div class="tiny" id="gc${i}"></div>`;goalCases.appendChild(d)});
function judgeGoal(i,v,btn){const box=btn.closest('.goalcase');box.classList.remove('ok','no');box.classList.add('done',v===goalData[i][1]?'ok':'no');document.getElementById('gc'+i).textContent=v===goalData[i][1]?'Так. Формулювання можна перевірити дією або результатом.':'Не зовсім. Шукайте конкретний результат, термін або спосіб перевірки.'}
const routeItems=['Знайти 2 хороші приклади й розібрати, що в них працює','Виділити 20 хв у календарі двічі на тиждень','Купити 17 маркерів, бо без них творчість точно не почнеться','Зробити першу маленьку роботу вже цього тижня','Попросити одну конкретну людину про відгук','Передивитися 40 випадкових роликів «для натхнення»','Зберегти результат у портфоліо з коротким поясненням','Обрати критерій: як я зрозумію, що стало краще'];
const rc=document.getElementById('routeChoices');routeItems.forEach((t,i)=>{const l=document.createElement('label');l.className='routeChoice';l.innerHTML=`<input type="checkbox" value="${i}"><span>${t}</span>`;l.querySelector('input').addEventListener('change',e=>{const checked=[...rc.querySelectorAll('input:checked')];if(checked.length>3){e.target.checked=false;return}l.classList.toggle('selected',e.target.checked);routeCount.textContent=rc.querySelectorAll('input:checked').length;routeProgress.style.width=(rc.querySelectorAll('input:checked').length/3*100)+'%'});rc.appendChild(l)});
function buildRoute(){const selected=[...rc.querySelectorAll('input:checked')].map(x=>routeItems[+x.value]);const g=goalText.value.trim();const date=goalDate.value;if(!g||!date||selected.length!==3){routeOutput.textContent='Потрібні: конкретна ціль, дата і рівно три кроки.';return}routeOutput.innerHTML=`<div class="callout teal"><b>Маршрут готовий:</b><br>${g}<br>До: ${date}<ol>${selected.map(x=>`<li>${x}</li>`).join('')}</ol></div>`}
let timerInt=null;function startTimer(){clearInterval(timerInt);let s=30;timer.textContent='00:30';timerText.textContent='Старт. Три речення — і жодного «ну, типу…».';timerInt=setInterval(()=>{s--;timer.textContent='00:'+String(s).padStart(2,'0');if(s<=0){clearInterval(timerInt);timerText.textContent='Час. Якщо вкладено сенс — чудово. Якщо лише прикметники — додаємо доказ.'}},1000)}
const questions=[
['Що найкраще описує портфоліо?',['Сховище всіх файлів','Добірка доказів умінь, досвіду й прогресу','Список оцінок за семестр','Альбом красивих фото'],1],
['Який підпис до роботи найсильніший?',['Я це робив/ла','Крута робота','Створив/ла інфографіку, зібрав/ла дані й пояснив/ла висновок команді','Мені подобається'],2],
['Що робить ціль перевірюваною?',['Багато мотиваційних слів','Конкретний результат або критерій','Секретність','Великий обсяг'],1],
['Яка ціль сформульована краще?',['Стати кращим дизайнером','До 15 жовтня створити 3 постери й порівняти їх за трьома критеріями','Більше старатися','Розвиватися'],1],
['Навіщо в портфоліо показувати «було → стало»?',['Щоб зайняти більше місця','Щоб показати прогрес','Щоб приховати слабкі роботи','Щоб не пояснювати результат'],1],
['Самооцінка на старті потрібна насамперед, щоб…',['приклеїти собі ярлик','порівнювати себе з усім класом','мати точку відліку для поступу','визначити професію назавжди'],2],
['Якщо ціль виявилася нереалістичною, найрозумніше…',['кинути все','змінити маршрут або масштаб цілі','зробити вигляд, що плану не було','додати ще більше пунктів'],1],
['Що варто вказувати в командному кейсі?',['Лише назву команди','Свою конкретну роль і внесок','Усі імена однокласників','Тільки оцінку'],1],
['Який перший крок кращий?',['Колись почати','Завтра 20 хвилин зробити перший ескіз','Стати експертом','Дочекатися натхнення'],1],
['Що НЕ обов’язково має бути в хорошому портфоліо?',['Доказ результату','Пояснення своєї ролі','Ідеальність без помилок','Приклад прогресу'],2]];
function validName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(x))}
function openQuiz(){gateErr.textContent='';if(!validName(fullName.value)||!studentClass.value.trim()){gateErr.textContent='Введіть ім’я, прізвище та клас.';return}gate.classList.add('hidden');quiz.classList.add('open');quiz.innerHTML=questions.map((q,i)=>`<fieldset class="q"><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</fieldset>`).join('')+'<button type="submit">Завершити тест</button>'}
function submitQuiz(e){e.preventDefault();let s=0;questions.forEach((q,i)=>{const a=quiz.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q[2])s++});const pct=s*10;const comment=s<=4?'Повторіть логіку портфоліо й цілі.':s<=7?'Достатній результат: основа вже є.':s<=9?'Добре: Ви розрізняєте докази, цілі й кроки.':'10/10 — структура не загубилася в мотиваційному тумані.';const now=new Date().toLocaleString('uk-UA');result.innerHTML=`<div class="resultCard"><div class="big">${s}/10 • ${pct}%</div><b>${fullName.value} • ${studentClass.value}</b><p>${comment}</p><p class="tiny">${now}</p><b>Зробіть скриншот цієї картки та надішліть учителю.</b></div>`;result.scrollIntoView({behavior:'smooth'});return false}