const correctSingle={1:'А',2:'Б',3:'Б',4:'В',5:'Б',6:'Б',7:'В',8:'А',9:'А',10:'В',11:'А',12:'Б'};
const explain={1:'Beta має менше 50% населення в urban centre і лише 17% у rural cells — це логіка towns/suburbs.',2:'Gamma має 58% населення в rural cells, але 18% зайнятих їздять до ядра — вище порогу 15% для commuting zone.',3:'FUA описує функціональні зв’язки; ключовий індикатор для commuting zone — потік зайнятих до ядра.',4:'Густота показує концентрацію населення, але не доводить глобальні фінансові чи управлінські функції.',5:'38,5% + 37,0% = 75,5% урбанізованого простору різних типів, а не частка населення у великих містах.',6:'Карта показує щільний пояс великих вузлів і зв’язків у Західній та Центральній Європі, а не рівномірне розміщення.',7:'Світове місто визначають функції та глобальні мережі, а не просто розмір.',8:'Метрополійний регіон охоплює функціонально пов’язану територію ширше адміністративного ядра.',9:'За двома заданими критеріями A має найкоротший доступ до станції та робочих місць.',10:'Високий ризик підтоплення — сильний просторовий обмежувач для C.',11:'A повторно використовує освоєну землю, не займає поля/зелений коридор і має добру доступність; ціна — рекультивація.',12:'Саме забруднення ґрунтів і реальна вартість очищення можуть радикально змінити оцінку A.'};
const multiCorrect={15:['1','2','3'],16:['1','2','3'],17:['1','2','3'],18:['1','2','3']};let scored={};
function chosenSingle(n){const x=document.querySelector('input[name="q'+n+'"]:checked');return x?x.value:null}
function setFb(id,msg,ok,kind){const e=document.getElementById(id);e.innerHTML=msg;e.className='feedback show '+(kind||(ok?'ok':'bad'))}
function checkRound(r){const ranges={1:[1,4],2:[5,8],3:[9,12]},ab=ranges[r],a=ab[0],b=ab[1];let got=0,missing=[];for(let n=a;n<=b;n++){const v=chosenSingle(n);if(!v){missing.push(n);continue}const ok=v===correctSingle[n];if(ok)got++;scored[n]=ok?1:0}if(missing.length){setFb('fb'+r,'Не всі відповіді позначені: '+missing.join(', ')+'. Команда має дати одну відповідь на кожне завдання.',false);return}let txt='<b>'+got+'/4.</b> ';for(let n=a;n<=b;n++)txt+='<br><b>'+n+'.</b> '+correctSingle[n]+' — '+explain[n];setFb('fb'+r,txt,got>=3,got>=3?'ok':'info');updateScore()}
function checkNumeric(){const a=Number(document.getElementById('num13').value),b=Number(document.getElementById('num14').value);if(!Number.isFinite(a)||!Number.isFinite(b)){setFb('fb4','Введіть обидві числові відповіді.',false);return}scored[13]=a===3000?2:0;scored[14]=b===18?2:0;const pts=scored[13]+scored[14];setFb('fb4','<b>'+pts+'/4.</b><br><b>13.</b> 72 000 ÷ 24 = <b>3000 ос./км²</b>.<br><b>14.</b> 1368 ÷ 7600 × 100 = <b>18%</b>. Це перевищує поріг 15% для commuting zone.',pts>=2,pts===4?'ok':'info');updateScore()}
document.querySelectorAll('.multi').forEach(cb=>cb.addEventListener('change',()=>{const n=cb.dataset.q,all=[...document.querySelectorAll('input[name="q'+n+'"]:checked')];if(all.length>3){cb.checked=false;return}document.getElementById('count'+n).textContent=[...document.querySelectorAll('input[name="q'+n+'"]:checked')].length}));
function checkRound5(){let total=0,problems=[];for(const n of [15,16,17,18]){const vals=[...document.querySelectorAll('input[name="q'+n+'"]:checked')].map(x=>x.value);if(vals.length!==3){problems.push(n);continue}const c=multiCorrect[n],p=vals.filter(v=>c.includes(v)).length;scored[n]=p;total+=p}if(problems.length){setFb('fb5','У завданнях '+problems.join(', ')+' потрібно обрати рівно три варіанти.',false);return}setFb('fb5','<b>'+total+'/12.</b> Правильні набори: <b>15 — 1,2,3; 16 — 1,2,3; 17 — 1,2,3; 18 — 1,2,3.</b><br>Пастка цього блоку — відрізняти прямі докази від речей, які просто «звучать міськими».',total>=9,total>=9?'ok':'info');updateScore()}
function updateScore(){let s=0;for(const v of Object.values(scored))s+=Number(v)||0;document.getElementById('score').textContent=s;document.getElementById('bar').style.width=Math.min(100,s/28*100)+'%';let t=s<=10?'Потрібно уважніше читати умову й відділяти показник від висновку.':s<=18?'Основа є; найбільше резерву в багатокритеріальних завданнях.':s<=24?'Сильний результат: команда добре читає дані й пастки.':'Дуже високий тренувальний результат: рішення спираються на дані, а не на інтуїцію.';document.getElementById('scoreText').textContent=t;return s}
function buildFinal(){const s=updateScore(),ch=document.getElementById('changed').value.trim(),take=document.getElementById('takeaway').value.trim(),e=document.getElementById('finalCard');e.style.display='block';e.innerHTML='<h3>Картка команди • URBAN NMT LAB</h3><p class="scorebig">'+s+'/28</p><p><b>Де змінили думку:</b> '+(ch||'—')+'</p><p><b>Головний принцип:</b> '+(take||'—')+'</p><p class="small">Це тренувальний бал уроку, а не офіційне переведення в шкалу НМТ. '+new Date().toLocaleString('uk-UA')+'</p>';e.scrollIntoView({behavior:'smooth'})}