const valueCount=document.getElementById('valueCount'),rankList=document.getElementById('rankList'),tradeFb=document.getElementById('tradeFb'),statementBox=document.getElementById('statementBox'),gate=document.getElementById('gate'),gateErr=document.getElementById('gateErr'),quiz=document.getElementById('quiz'),result=document.getElementById('result'),fullName=document.getElementById('fullName'),studentClass=document.getElementById('studentClass');
function scenario(btn,text){const box=btn.closest('.scenario');box.querySelector('.feedback').textContent='Ваш вибір: '+text+'. Це не діагноз — просто один сигнал у профілі.'}
const interests=[['Аналітика','розбирати дані, закономірності'],['Творчість','вигадувати, оформлювати, створювати'],['Люди','спілкуватися, навчати, підтримувати'],['Техніка','налаштовувати, конструювати, ремонтувати'],['Природа','працювати з живими системами й довкіллям'],['Організація','планувати, координувати, доводити до результату'],['Дослідження','ставити запитання, перевіряти гіпотези'],['Рух','бути в дії, змінювати середовище, працювати не лише за столом']];
const interestSliders=document.getElementById('interestSliders'),interestBars=document.getElementById('interestBars');interests.forEach((it,i)=>{const s=document.createElement('div');s.className='slider';s.innerHTML=`<label>${it[0]} <span id="iv${i}">2</span></label><div class="tiny">${it[1]}</div><input type="range" min="0" max="5" value="2" id="is${i}">`;interestSliders.appendChild(s);const b=document.createElement('div');b.className='barrow';b.innerHTML=`<span>${it[0]}</span><div class="bar"><i id="ib${i}" style="width:40%"></i></div><b id="in${i}">2</b>`;interestBars.appendChild(b);s.querySelector('input').addEventListener('input',updateInterests)});
function updateInterests(){let vals=interests.map((_,i)=>+document.getElementById('is'+i).value);vals.forEach((v,i)=>{document.getElementById('iv'+i).textContent=v;document.getElementById('in'+i).textContent=v;document.getElementById('ib'+i).style.width=(v/5*100)+'%'});let max=Math.max(...vals);let top=vals.map((v,i)=>v===max?interests[i][0]:null).filter(Boolean);interestTop.textContent='Найсильніший сигнал зараз: '+top.join(', ')+'. Перевіряйте його досвідом, а не лише шкалою.';updateStatement()}
const values=['Свобода','Стабільність','Високий дохід','Творчість','Користь людям','Визнання','Баланс часу','Навчання й розвиток','Команда','Самостійність','Передбачуваність','Пригоди / зміни'];const selectedValues=[];const cloud=document.getElementById('valueCloud');values.forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.className='valueChip';b.textContent=v;b.onclick=()=>toggleValue(v,b);cloud.appendChild(b)});
function toggleValue(v,b){const idx=selectedValues.indexOf(v);if(idx>=0){selectedValues.splice(idx,1);b.classList.remove('selected')}else{if(selectedValues.length>=5)return;selectedValues.push(v);b.classList.add('selected')}renderValues();updateStatement()}
function renderValues(){valueCount.textContent=selectedValues.length;[...cloud.children].forEach(b=>b.classList.toggle('locked',selectedValues.length>=5&&!b.classList.contains('selected')));rankList.innerHTML=selectedValues.map((v,i)=>`<div class="rankitem"><span class="ranknum">${i+1}</span><b>${v}</b></div>`).join('')}
function resetValues(){selectedValues.splice(0);[...cloud.children].forEach(b=>b.classList.remove('selected','locked'));renderValues();updateStatement()}
const collisions=[['Свобода графіка','погодитися з меншою передбачуваністю'],['Високий дохід','мати більше відповідальності або конкуренції'],['Творчість','частіше отримувати суб’єктивний зворотний зв’язок'],['Допомога людям','мати емоційне навантаження'],['Стабільність','мати більше правил і менше різких змін'],['Швидкий розвиток','часто вчитися поза зоною комфорту']];const cg=document.getElementById('collisionGrid');collisions.forEach((c,i)=>{const d=document.createElement('div');d.className='scenario collision';d.innerHTML=`<b>${c[0]}</b><p>Ціна: ${c[1]}.</p><button type="button" onclick="pickCollision(this,1)">Готовий/а частіше</button><button type="button" class="secondary" onclick="pickCollision(this,0)">Скоріше ні</button>`;cg.appendChild(d)});function pickCollision(btn,v){const b=btn.closest('.collision');b.classList.add('selected');b.dataset.pick=v;tradeFb.textContent='Добре. Пріоритет стає реальним саме тоді, коли Ви бачите його ціну.';updateStatement()}
const criteria=[['дохід','Дохід'],['stability','Стабільність'],['creative','Творчість'],['people','Користь людям'],['freedom','Свобода']];const weightGrid=document.getElementById('weightGrid');criteria.forEach((c,i)=>{const d=document.createElement('div');d.className='weight';d.innerHTML=`<label>${c[1]} <span id="wv${i}">3</span></label><input id="w${i}" type="range" min="1" max="5" value="3">`;weightGrid.appendChild(d);d.querySelector('input').addEventListener('input',scoreJobs)});
const jobData=[{n:'A • Дослідницька лабораторія',s:[3,4,4,4,3],t:['аналіз','навчання','точність']},{n:'B • Креативна студія',s:[3,2,5,3,4],t:['ідеї','проєкти','зміни']},{n:'C • Соціальний проєкт',s:[2,3,4,5,3],t:['люди','вплив','команда']},{n:'D • Технічна служба',s:[4,5,2,3,2],t:['стабільність','системність','відповідальність']}];const jobs=document.getElementById('jobs');jobData.forEach((j,i)=>{const d=document.createElement('div');d.className='job';d.id='job'+i;d.innerHTML=`<b>${j.n}</b><div class="score" id="js${i}">0</div><div class="traits">${j.t.map(x=>`<span>${x}</span>`).join('')}</div>`;jobs.appendChild(d)});
function scoreJobs(){const w=criteria.map((_,i)=>+document.getElementById('w'+i).value);w.forEach((v,i)=>document.getElementById('wv'+i).textContent=v);const scores=jobData.map(j=>j.s.reduce((a,v,i)=>a+v*w[i],0));const max=Math.max(...scores);scores.forEach((s,i)=>{document.getElementById('js'+i).textContent=s;document.getElementById('job'+i).classList.toggle('best',s===max)});updateStatement()}scoreJobs();updateInterests();
function updateStatement(){if(!document.getElementById('is0'))return;const vals=interests.map((_,i)=>+document.getElementById('is'+i).value);const max=Math.max(...vals);const topI=vals.map((v,i)=>v===max?interests[i][0]:null).filter(Boolean).slice(0,2).join(' + ');const val=selectedValues.slice(0,2).join(' і ')||'ще не обрані цінності';const best=[...document.querySelectorAll('.job.best b')].map(x=>x.textContent).join(' / ')||'матриця ще не порахована';statementBox.innerHTML=`<b>Чернетка:</b> «Зараз мене найбільше цікавлять <b>${topI}</b>. Для мене важливі <b>${val}</b>. У модельній матриці найкраще збігається <b>${best}</b>, але це лише гіпотеза: я маю перевірити її реальними прикладами професій і досвідом».`}
const questions=[
['Що таке професійний інтерес?',['Професія, у якій Ви вже найкращий/а','Схильність уваги й цікавості до певних видів діяльності','Гарантована майбутня професія','Рейтинг зарплат'],1],
['Що таке цінність у контексті вибору праці?',['Те, що для Вас важливо в роботі й житті','Лише розмір зарплати','Назва професії','Оцінка в атестаті'],0],
['Коли пріоритет стає реальним?',['Коли красиво звучить','Коли впливає на вибір між альтернативами','Коли його обрав друг','Коли є один тест'],1],
['Чому два учні з однаковими інтересами можуть обрати різні професії?',['Бо один помилився','Бо мають різні цінності, умови й контекст','Це неможливо','Через назву професії'],1],
['Що показує матриця з вагами критеріїв?',['Єдину правильну професію','Як результат змінюється залежно від пріоритетів','IQ','Рівень успішності'],1],
['Який висновок коректний після профорієнтаційного тесту?',['Це остаточний вирок','Це гіпотеза для подальшої перевірки','Треба одразу подавати документи','Інші дані не потрібні'],1],
['Чому важливо бачити «ціну» пріоритету?',['Щоб відмовитися від усіх бажань','Щоб розуміти компроміси','Щоб обрати найдорожчу професію','Щоб не аналізувати умови'],1],
['Що краще робити з цінностями через рік?',['Ніколи не переглядати','Перевірити, чи вони змінилися з досвідом','Скопіювати чужі','Видалити рейтинг'],1],
['Який приклад є професійним пріоритетом?',['Люблю синій колір','Мені важлива автономність у роботі','Маю рюкзак','Подобається п’ятниця'],1],
['Що найкраще робити після уроку?',['Вибрати одну професію назавжди','Перевірити 2–3 напрями через реальні описи, людей і маленькі проби','Не думати про це','Довіритися випадковому тесту'],1]];
function validName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(x))}function openQuiz(){gateErr.textContent='';if(!validName(fullName.value)||!studentClass.value.trim()){gateErr.textContent='Введіть ім’я, прізвище та клас.';return}gate.classList.add('hidden');quiz.classList.add('open');quiz.innerHTML=questions.map((q,i)=>`<fieldset class="q"><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</fieldset>`).join('')+'<button type="submit">Завершити тест</button>'}
function submitQuiz(e){e.preventDefault();let s=0;questions.forEach((q,i)=>{const a=quiz.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q[2])s++});const pct=s*10;const c=s<=4?'Поверніться до відмінностей між інтересами, цінностями й пріоритетами.':s<=7?'Основа є. Потренуйтеся бачити компроміси.':s<=9?'Добре: Ви розумієте логіку багатокритеріального вибору.':'10/10 — жоден магічний тест не переміг Ваше мислення.';const now=new Date().toLocaleString('uk-UA');result.innerHTML=`<div class="resultCard"><div class="big">${s}/10 • ${pct}%</div><b>${fullName.value} • ${studentClass.value}</b><p>${c}</p><p class="tiny">${now}</p><b>Зробіть скриншот картки й надішліть учителю.</b></div>`;result.scrollIntoView({behavior:'smooth'});return false}