let azTarget=135;
let selectedProfile='';
function reveal(id){const el=document.getElementById(id);el.style.display=el.style.display==='block'?'none':'block'}
function priority(btn){document.querySelectorAll('#problem .logic-buttons button').forEach(b=>b.style.background='#e8efe5');btn.style.background='#d9ead9';const box=document.getElementById('priorityFb');box.style.display='block';box.innerHTML='Так. Для обґрунтованого рішення потрібна <b>комбінація</b> трьох типів даних: напрям, вертикальний перепад і форма рельєфу. Один показник не замінює решту.'}
function setAzimuth(v){document.getElementById('azValue').textContent=v;document.getElementById('needle').style.transform=`translate(-50%,-100%) rotate(${v}deg)`}
function angularDiff(a,b){let d=Math.abs(a-b)%360;return Math.min(d,360-d)}
function checkAzimuth(){const v=Number(document.getElementById('azSlider').value);const d=angularDiff(v,azTarget);const fb=document.getElementById('azFb');if(d<=5){fb.className='feedback ok';fb.innerHTML=`✓ Точно: ціль має азимут приблизно <b>${azTarget}°</b>. Похибка ${d}°.`}else if(d<=15){fb.className='feedback';fb.innerHTML=`Майже. Ви відхилилися на ${d}°. Пам’ятайте: відлік іде від півночі за годинниковою стрілкою.`}else{fb.className='feedback no';fb.innerHTML=`Поки що ні. Різниця ${d}°. Спершу знайдіть північ, а далі оцініть сектор 0–90–180–270°.`}}
function newAzMission(){const arr=[35,70,110,145,205,250,300,330];azTarget=arr[Math.floor(Math.random()*arr.length)];document.getElementById('targetNeedle').style.transform=`translate(-50%,-100%) rotate(${azTarget}deg)`;document.getElementById('azFb').textContent='';document.getElementById('azSlider').value=0;setAzimuth(0)}
function checkHeight(){const v=Number(document.getElementById('relHeight').value);const fb=document.getElementById('heightFb');if(v===275){fb.className='feedback ok';fb.textContent='✓ Правильно: 917 − 642 = 275 м.'}else{fb.className='feedback no';fb.textContent='Спробуйте ще: відносна висота — це різниця абсолютних висот двох точок.'}}
function selectProfile(id,el){selectedProfile=id;document.querySelectorAll('.profile-option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function checkProfile(){const fb=document.getElementById('profileFb');if(!selectedProfile){fb.className='feedback no';fb.textContent='Спочатку оберіть один із профілів.';return}if(selectedProfile==='p2'){fb.className='feedback ok';fb.innerHTML='✓ Профіль B: уздовж A–B є <b>підйом на перше підвищення → спуск у сідловину → другий підйом → спуск до B</b>.'}else{fb.className='feedback no';fb.textContent='Не збігається з картою: лінія A–B перетинає два окремі підвищення, між якими є зниження.'}}
function logic(btn,type){const fb=document.getElementById('logicFb');fb.style.display='block';if(type==='good'){fb.innerHTML='✓ Це найсильніше твердження. Воно поєднує кілька незалежних доказів і не робить висновок за одним показником.'}else{fb.innerHTML='✗ Це спрощення. Для висновку треба відрізняти абсолютну висоту від набору висоти й не плутати коротку відстань із легкою прохідністю.'}}
function validFullName(value){const parts=value.trim().replace(/\s+/g,' ').split(' ');return parts.length>=2&&parts.every(p=>/^[А-ЯІЇЄҐа-яіїєґA-Za-z'’\-]+$/.test(p))}
const startQuiz=document.getElementById('startQuiz');
startQuiz.addEventListener('click',()=>{const n=document.getElementById('fullName').value;const c=document.getElementById('studentClass').value;const err=document.getElementById('gateError');if(!validFullName(n)||!c){err.textContent='Введіть ім’я, прізвище та клас.';return}err.textContent='';document.getElementById('identityGate').classList.add('hidden');document.getElementById('quiz').classList.remove('hidden')});
function checkedValues(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value).sort()}
function exact(arr,expected){return arr.length===expected.length&&arr.every((v,i)=>v===expected.slice().sort()[i])}
function radio(name){const e=document.querySelector(`input[name="${name}"]:checked`);return e?e.value:''}
function gradeQuiz(){let s=0;if(radio('q1')==='135')s++;if(radio('q2')==='70')s++;if(radio('q3')==='b')s++;if(radio('q4')==='hill')s++;if(exact(checkedValues('q5'),['close','rise']))s++;if(exact(checkedValues('q6'),['elevations','intersections','line']))s++;if(document.getElementById('m1').value==='angle'&&document.getElementById('m2').value==='sea'&&document.getElementById('m3').value==='difference'&&document.getElementById('m4').value==='section')s++;if(document.getElementById('q8').value==='correct')s++;if(radio('q9')==='scale')s++;if(radio('q10')==='c')s++;const pct=s*10;let comment=s<=4?'Потрібно повторити алгоритми й поняття.':s<=7?'Достатній рівень: основа є, але перевірте профілі та логіку доказів.':s<=9?'Добре: ви впевнено читаєте топографічні дані.':'Відмінно: усі 10 завдань виконано правильно.';document.getElementById('scoreText').textContent=`${s}/10 • ${pct}%`;const dt=new Date();document.getElementById('resultMeta').innerHTML=`<b>${escapeHtml(document.getElementById('fullName').value)}</b> • ${escapeHtml(document.getElementById('studentClass').value)}<br>Тема: Азимути, абсолютні й відносні висоти, профіль місцевості<br>${dt.toLocaleString('uk-UA')}<br><b>${comment}</b>`;document.getElementById('resultCard').style.display='block';document.getElementById('resultCard').scrollIntoView({behavior:'smooth',block:'center'})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function retakeQuiz(){if(!confirm('Очистити відповіді й пройти тест ще раз? Ім’я та клас залишаться.'))return;document.getElementById('quiz').reset();document.getElementById('resultCard').style.display='none';document.getElementById('quizSection').scrollIntoView({behavior:'smooth'})}
setAzimuth(0);