const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$$('.choices').forEach(group=>group.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const out=group.nextElementSibling;out.innerHTML=b.dataset.answer==='right'?'✅ Так. Висновок спирається на форму рельєфу й батиметричні дані.':'↺ Не поспішайте: шукайте не окремий факт, а поєднання глибини, форми та положення об’єкта.';}));
$$('.term-grid button').forEach(b=>b.addEventListener('click',()=>$('#termFeedback').textContent=b.dataset.text));
$('#depth').addEventListener('input',e=>{const v=+e.target.value;$('#depthValue').textContent=`${v.toLocaleString('uk-UA')} м`;$('#depthMarker').style.left=`${Math.min(100,Math.max(0,v/110))}%`;let zone=v<200?'материкова обмілина':v<3000?'материковий схил / перехідна зона':v<6000?'ложе океану':v<8000?'глибоководна область': 'зона океанічних жолобів';$('#depthZone').textContent=`Ймовірна зона: ${zone}.`;});
$('#checkMatch').addEventListener('click',()=>{let ok=0;$$('#matchQuiz select').forEach(s=>{if(s.value===s.dataset.ok)ok++});$('#matchFeedback').textContent=`${ok}/5 правильно. `+(ok===5?'Ви читаєте профіль океану як геоморфолог.':'Перевірте: шельф — мілководна окраїна материка; хребет — підводна гірська система; жолоб — вузьке дуже глибоке зниження.');});
$$('.check').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.target).classList.toggle('show')));
const lock=()=>{const n=$('#name').value.trim(),s=$('#surname').value.trim(),c=$('#class').value;const open=n.length>1&&s.length>1&&c;$('#quiz').classList.toggle('locked',!open);$('#unlockMsg').textContent=open?`Тест відкрито для: ${s} ${n}, ${c}.`:'Введіть ім’я, прізвище та клас, щоб відкрити тест.';};['#name','#surname','#class'].forEach(id=>$(id).addEventListener('input',lock));
$('#checkQuiz').addEventListener('click',()=>{if($('#quiz').classList.contains('locked'))return;let score=0;$$('.question').forEach(q=>{const checked=q.querySelector('input:checked');if(checked&&checked.value===q.dataset.ok)score++;});$('#score').textContent=`Результат: ${score}/10 балів.`;});
if(window.L){const map=L.map('map',{worldCopyJump:true}).setView([16,145],3);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}',{maxZoom:10,attribution:'Tiles © Esri; bathymetry sources include GEBCO, NOAA, IHO'}).addTo(map);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Reference/MapServer/tile/{z}/{y}/{x}',{maxZoom:10,attribution:''}).addTo(map);const pts=[[11.35,142.2,'Маріанська западина / Challenger Deep'],[0,-29,'Серединно-Атлантичний хребет'],[20,-65,'Пуерто-Риканський жолоб'],[-23,-174,'Тонга — Кермадек'],[19,-155,'Гавайський підводний вулканічний ланцюг']];pts.forEach(([a,b,t])=>L.marker([a,b]).addTo(map).bindPopup(`<b>${t}</b><br>Збільшіть масштаб і прочитайте батиметричне забарвлення.`));}
