const $=id=>document.getElementById(id);
function show(id,text,type='neutral'){const el=$(id);el.textContent=text;el.className='feedback show '+type}
function checkMyth(){const v=document.querySelector('input[name="myth"]:checked');if(!v){show('fb-myth','Оберіть твердження. Географічна телепатія сьогодні не зараховується.','bad');return}if(v.value==='b')show('fb-myth','Так. Більша людність міста не гарантує вищої густоти: вирішальним є ще й розмір території. Повернемося до цього наприкінці.','good');else show('fb-myth','Це твердження якраз може бути правильним. Спробуйте перевірити, який показник воно описує.','neutral')}
function checkSettlements(){const a=$('sA').value,b=$('sB').value,c=$('sC').value;if(a==='village'&&b==='town'&&c==='city')show('fb-settle','Вірно: A — село, B — селище, C — місто за чинними українськими критеріями.','good');else show('fb-settle','Перевірте пороги: менше 5 тис. + садибна забудова; від 5 тис. + садибна; від 10 тис. + переважно компактна забудова.','bad')}
function updateDensity(){const pop=+$('popRange').value,area=+$('areaRange').value,d=Math.round(pop/area);$('popOut').textContent=pop.toLocaleString('uk-UA');$('areaOut').textContent=area.toLocaleString('uk-UA');$('densityOut').textContent=d.toLocaleString('uk-UA');renderDots(Math.min(100,Math.max(8,Math.round(d/12))))}
function renderDots(n){const box=$('dots');box.innerHTML='';for(let i=0;i<100;i++){const s=document.createElement('span');s.className='dot'+(i<n?'':' hidden');box.appendChild(s)}}
function checkDensityHyp(){const v=$('densityHyp').value;if(v==='up')show('fb-density','Так. За сталої кількості населення приблизне удвічі зменшення площі приблизно подвоює густоту.','good');else show('fb-density','Подумайте за формулою N ÷ S: якщо знаменник меншає, а чисельник сталий, частка зростає.','bad')}
function checkEvidence(){const ok=$('ev1').value==='A'&&$('ev2').value==='B'&&$('ev3').value==='B';if(ok)show('fb-evidence','Саме так: рівень урбанізації, густота й темп урбанізації — різні показники.','good');else show('fb-evidence','Щось змішалося. Порівняйте окремо: % міського населення, осіб/км² і швидкість зростання міст.','bad')}
function checkLogic(){if($('logic').value==='no')show('fb-logic','Вірно. 90% — це структура розселення за типом поселень, а не число осіб на одиницю площі.','good');else show('fb-logic','Ні. Тут підмінили один показник іншим: урбанізацію — густотою.','bad')}
function validFullName(value){const parts=value.trim().replace(/\s+/g,' ').split(' ');return parts.length>=2&&parts.every(p=>/^[А-ЯІЇЄҐа-яіїєґA-Za-z'’\-]+$/.test(p))}
function startQuiz(){const n=$('fullName').value,c=$('studentClass').value.trim();if(!validFullName(n)||!c){show('gateError','Введіть ім’я, прізвище та клас.','bad');return}$('quizGate').style.display='none';$('quizForm').style.display='block';$('quizForm').scrollIntoView({behavior:'smooth',block:'start'})}
function exactChecked(name,expected){const got=[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value).sort();return got.length===expected.length&&got.every((v,i)=>v===expected.slice().sort()[i])}
function val(name){const x=document.querySelector(`[name="${name}"]:checked`);return x?x.value:''}
function gradeQuiz(e){e.preventDefault();let s=0;
if(val('q1')==='b')s++;if(val('q2')==='x')s++;if(val('q3')==='sub')s++;if(val('q4')==='pseudo')s++;
if(exactChecked('q5',['area','pop']))s++;if(exactChecked('q6',['commute','core','links']))s++;
if(document.querySelector('[name="q7a"]').value==='1'&&document.querySelector('[name="q7b"]').value==='2'&&document.querySelector('[name="q7c"]').value==='3')s++;
if(document.querySelector('[name="q8"]').value.replace(/\s/g,'')==='3124')s++;
if(val('q9')==='quality')s++;if(val('q10')==='b')s++;
const pct=s*10;const name=$('fullName').value.trim().replace(/\s+/g,' '),cls=$('studentClass').value.trim();const now=new Date();$('scoreLine').textContent=`${s}/10 • ${pct}%`;$('resultMeta').innerHTML=`<b>${name}</b> • ${cls}<br>Тема: Розселення — населені пункти, густота й урбанізація<br>${now.toLocaleString('uk-UA')}`;$('levelComment').textContent=s<=4?'Потрібно повторити різницю між густотою, рівнем урбанізації та урбанізаційними процесами.':s<=7?'Достатній результат. Перевірте логіку завдань на дані й поняття.':s<=9?'Добре. Ви впевнено розрізняєте показники й процеси.':'Відмінно: показники, причинність і межі висновку не переплутані.';$('quizResult').style.display='block';$('quizForm').style.display='none';$('quizResult').scrollIntoView({behavior:'smooth'});return false}
function retryQuiz(){if(!confirm('Очистити відповіді тесту? Ім’я та клас залишаться.'))return;$('quizForm').reset();$('quizResult').style.display='none';$('quizForm').style.display='block';$('quizForm').scrollIntoView({behavior:'smooth'})}
updateDensity();