(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const show=(el,msg,bad=false)=>{if(!el)return;el.textContent=msg;el.classList.add('show');el.classList.toggle('bad',!!bad)};
$$('[data-single="hypothesis"] button').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-single="hypothesis"] button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const msg=btn.dataset.value==='both'?'Найсильніша стартова гіпотеза. Міграція змінює структуру населення, а структура впливає на наслідки міграції. Тепер це треба довести даними.':'Це може бути важливим чинником, але сам по собі він не пояснює всю систему. Перевіримо взаємодію показників.';show($('#hypothesisFeedback'),msg,false);}));
$$('#migrationCards .scenario').forEach(card=>{const correct=card.dataset.answer;$$('.mini-options button',card).forEach(btn=>btn.addEventListener('click',()=>{$$('.mini-options button',card).forEach(b=>b.classList.remove('selected','correct','wrong'));btn.classList.add('selected');const ok=btn.dataset.pick===correct;btn.classList.add(ok?'correct':'wrong');const label=correct==='internal'?'внутрішня міграція':correct==='international'?'міжнародна міграція':'не міграція у демографічному сенсі';$('.mini-feedback',card).textContent=ok?'✓ Так. Це '+label+'.':'Не зовсім. Найточніше: '+label+'.';}));});
$('#checkMapEvidence')?.addEventListener('click',()=>{const chosen=$$('#mapEvidence input:checked').map(x=>x.value).sort().join('');show($('#mapEvidenceFeedback'),chosen==='ac'?'✓ Саме так. Карта показує просторові відмінності частки, але не абсолютну кількість і не причини кожного переїзду.':'Потрібно рівно два твердження, які карта справді доводить. Пильнуйте різницю між «часткою» і «кількістю», а також між «показує» і «пояснює».',chosen!=='ac');});
$('#calcBalance')?.addEventListener('click',()=>{const a=Number($('#arrivals').value),d=Number($('#departures').value);const r=a-d;const sign=r>0?'+':'';const word=r>0?'додатне':r<0?'від’ємне':'нульове';$('#balanceResult').innerHTML=`Сальдо: <strong>${sign}${r.toLocaleString('uk-UA')}</strong> осіб — ${word}.`;});
$$('#pyramidClaim button').forEach(btn=>btn.addEventListener('click',()=>{$$('#pyramidClaim button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const ok=btn.dataset.value==='b';show($('#pyramidFeedback'),ok?'✓ Так. Піраміда добре показує структуру і аномалії, але причини потрібно перевіряти іншими джерелами.':'Ні. Піраміда показує і вік, і стать, але не може сама довести конкретну причину кожного «провалу».',!ok);}));
$$('.level-tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.level-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.level);}));
$$('#duelChoices button').forEach(btn=>btn.addEventListener('click',()=>{$$('#duelChoices button').forEach(b=>b.classList.remove('correct','wrong'));const ok=btn.dataset.correct==='true';btn.classList.add(ok?'correct':'wrong');show($('#duelFeedback'),ok?'✓ Саме так. Дані про вік фіксують зміну структури, але не встановлюють ані напрямок руху, ані мотив. Потрібні міграційні дані й контекст.':'Це слабкий висновок. Тут плутають спостереження з причиною. Знайдіть варіант, який прямо говорить про межу даних.',!ok);}));
$('#checkCer')?.addEventListener('click',()=>{const vals=[$('#cerClaim').value,$('#cerEvidence').value,$('#cerReason').value].map(v=>v.trim());const complete=vals.every(v=>v.length>=20);show($('#cerFeedback'),complete?'✓ Конструкція повна. Перевірте ще одне: у доказі має бути конкретний показник/карта, а в поясненні — зв’язок і хоча б одна межа висновку.':'Заповніть усі три частини змістовно. CER працює лише тоді, коли є і твердження, і конкретний доказ, і пояснення зв’язку/обмеження.',!complete);});
function validFullName(value){const parts=value.trim().replace(/\s+/g,' ').split(' ');return parts.length>=2&&parts.every(p=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(p));}
$('#startQuiz')?.addEventListener('click',()=>{const name=$('#fullName').value.trim();const cls=$('#studentClass').value.trim();if(!validFullName(name)||!cls){show($('#gateFeedback'),'Введіть ім’я та прізвище (щонайменше два слова, без цифр) і оберіть клас.',true);return;}$('#identityGate').hidden=true;$('#quiz').hidden=false;$('#quiz').scrollIntoView({behavior:'smooth',block:'start'});});
const exactSet=(name,expected)=>$$(`input[name="${name}"]:checked`).map(x=>x.value).sort().join('')===expected.slice().sort().join('');
$('#quiz')?.addEventListener('submit',e=>{e.preventDefault();let score=0;const radio=(name,val)=>$(`input[name="${name}"]:checked`)?.value===val;if(radio('q1','b'))score++;if(radio('q2','c'))score++;if(radio('q3','b'))score++;if(radio('q4','b'))score++;if(exactSet('q5',['a','c']))score++;if(exactSet('q6',['a','c']))score++;if($('select[name="q7a"]').value==='B'&&$('select[name="q7b"]').value==='A'&&$('select[name="q7c"]').value==='C')score++;if(($('input[name="q8"]').value||'').trim().toUpperCase()==='CBDA')score++;if(radio('q9','b'))score++;if(radio('q10','c'))score++;const name=$('#fullName').value.trim().replace(/\s+/g,' ');const cls=$('#studentClass').value;const pct=score*10;const level=score<=4?'Потрібно повторити ключові поняття й попрацювати з доказами.':score<=7?'Достатній результат. Перевірте логічні пастки та різницю між часткою й абсолютним числом.':score<=9?'Добре. Ви коректно працюєте з більшістю демографічних доказів.':'Відмінно. Усі 10 завдань розв’язані коректно.';const now=new Date();const stamp=now.toLocaleString('uk-UA');const card=$('#resultCard');card.innerHTML=`<div class="result-top"><div><span class="source-chip">Результат тесту</span><h2>${escapeHtml(name)}</h2><div>${escapeHtml(cls)} • Міграції та статево-віковий склад</div></div><div class="result-score">${score}/10</div></div><div class="result-meta"><div><b>${pct}%</b><br><span class="small">виконання</span></div><div><b>${stamp}</b><br><span class="small">дата і час</span></div></div><div class="result-note">${level}</div><p><strong>Зробіть скриншот цієї картки та надішліть учителю.</strong></p><div class="result-actions no-print"><button type="button" class="btn primary" id="printResult">Друк / PDF</button><button type="button" class="btn ghost" id="retryQuiz">Пройти ще раз</button></div>`;card.hidden=false;$('#quiz').hidden=true;card.scrollIntoView({behavior:'smooth',block:'center'});$('#printResult')?.addEventListener('click',()=>window.print());$('#retryQuiz')?.addEventListener('click',()=>{if(!confirm('Пройти тест ще раз? Ім’я та клас залишаться, відповіді буде очищено.'))return;e.target.reset();card.hidden=true;e.target.hidden=false;e.target.scrollIntoView({behavior:'smooth'});});});
function escapeHtml(s){return s.replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
let large=false;$('#textSize')?.addEventListener('click',()=>{large=!large;document.documentElement.style.setProperty('--text',large?'19px':'17px');$('#textSize').textContent=large?'A−':'A+';});$('#toTop')?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
})();
