'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const showFeedback=(el,kind,text)=>{el.className='feedback show '+kind;el.textContent=text};
const safeStore=(key,value)=>{try{localStorage.setItem(key,value)}catch(e){}};
const safeGet=key=>{try{return localStorage.getItem(key)||''}catch(e){return ''}};

const hypothesis=$('#hypothesis'); hypothesis.value=safeGet('pp5_l2_hyp'); $('#saveHyp').addEventListener('click',()=>{safeStore('pp5_l2_hyp',hypothesis.value.trim());$('#hypFeedback').classList.add('show')});

const classifyStates=['none','discovery','invention','both']; const labels={none:'Натисніть, щоб обрати →',discovery:'🔎 Відкриття',invention:'🛠️ Винахід',both:'🔁 Обидва'};
$$('.classify-card').forEach(card=>card.addEventListener('click',()=>{let i=classifyStates.indexOf(card.dataset.state);card.dataset.state=classifyStates[(i+1)%classifyStates.length];card.querySelector('.choice').textContent=labels[card.dataset.state]}));
$('#checkClassify').addEventListener('click',()=>{const cards=$$('.classify-card');const unanswered=cards.filter(c=>c.dataset.state==='none').length;const score=cards.filter(c=>c.dataset.state===c.dataset.answer).length;showFeedback($('#classifyFeedback'),unanswered?'warn':score===cards.length?'good':'warn',unanswered?`Ще ${unanswered} карток без відповіді.`:`Правильно ${score} із ${cards.length}. Відкриття — нове знання про те, що існувало; винахід — створене людиною рішення.`)});

const cases={burr:{img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Burdock_Hooks.jpg/960px-Burdock_Hooks.jpg',caption:'Реп’ях: дрібні гачки чіпляються до шерсті й тканини.',pair:'hooks'},lotus:{img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Lotus_leaf_with_waterdrops.jpg/960px-Lotus_leaf_with_waterdrops.jpg',caption:'Листок лотоса: вода збирається в краплі й легко скочується.',pair:'clean'},gecko:{img:'https://upload.wikimedia.org/wikipedia/commons/c/c9/Tokay_foot.jpg',caption:'Лапа гекона: спеціалізовані подушечки й мікроструктури забезпечують зчеплення.',pair:'adhesion'},kingfisher:{img:'https://commons.wikimedia.org/wiki/Special:FilePath/Common%20Kingfisher-Alcedo%20atthis.jpg?width=1000',caption:'Рибалочка: довгий вузький дзьоб допомагає входити у воду з малим плескотом.',pair:'streamline'}};
let currentCase='burr', selectedPair='';
$$('#caseTabs button').forEach(btn=>btn.addEventListener('click',()=>{currentCase=btn.dataset.case;$$('#caseTabs button').forEach(b=>b.classList.toggle('active',b===btn));$$('.case-pane').forEach(p=>p.classList.remove('active'));$('#case'+currentCase[0].toUpperCase()+currentCase.slice(1)).classList.add('active');$('#caseImage').src=cases[currentCase].img;$('#caseCaption').textContent=cases[currentCase].caption;selectedPair='';$$('.pair-btn').forEach(b=>b.classList.remove('active'));$('#pairFeedback').className='feedback'}));
$$('.pair-btn').forEach(btn=>btn.addEventListener('click',()=>{selectedPair=btn.dataset.pair;$$('.pair-btn').forEach(b=>b.classList.toggle('active',b===btn))}));
$('#checkPair').addEventListener('click',()=>{if(!selectedPair)return showFeedback($('#pairFeedback'),'warn','Спершу оберіть технічну пару.');showFeedback($('#pairFeedback'),selectedPair===cases[currentCase].pair?'good':'warn',selectedPair===cases[currentCase].pair?'Так. Ви поєднали природну функцію з відповідним технічним принципом.':'Не зовсім. Дивіться не на зовнішню схожість, а на функцію природної структури.')});

$('#checkScientistSource').addEventListener('click',()=>{const v=$('input[name="scientistSource"]:checked')?.value;if(!v)return showFeedback($('#scientistSourceFeedback'),'warn','Оберіть один варіант.');showFeedback($('#scientistSourceFeedback'),v==='b'?'good':'warn',v==='b'?'Так. Музейна сторінка з описом джерел і методів дає перевірювану основу для картки.':'Такого повідомлення недостатньо: потрібні автор, джерело й перевірювані факти.')});

$$('.mission-tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.mission-tabs button').forEach(b=>b.classList.toggle('active',b===btn));$$('.mission-pane').forEach(p=>p.classList.remove('active'));$('#mission'+({base:'Base',middle:'Middle',high:'High'}[btn.dataset.level])).classList.add('active')}));
$('#missionText').value=safeGet('pp5_l2_mission');$('#saveMission').addEventListener('click',()=>{safeStore('pp5_l2_mission',$('#missionText').value.trim());$('#missionFeedback').classList.add('show')});

$('#checkDuel').addEventListener('click',()=>{const got=$$('input[name="duelEvidence"]:checked').map(x=>x.value).sort().join('');showFeedback($('#duelFeedback'),got==='ac'?'good':'warn',got==='ac'?'Так. Сильні докази — документована історія розробки та незалежне підтвердження, а не сама візуальна схожість.':'Оберіть лише ті джерела, які документують причинний зв’язок між природним принципом і технічним рішенням.')});

$('#checkCer').addEventListener('click',()=>{const vals=[$('#claim').value.trim(),$('#evidenceText').value.trim(),$('#reasoning').value.trim()];const filled=vals.filter(v=>v.length>=15).length;showFeedback($('#cerFeedback'),filled===3?'good':'warn',filled===3?'CER повний: є твердження, конкретний доказ і пояснення зв’язку.':'Заповніть усі три частини. Доказ має бути конкретним фактом або джерелом, а пояснення — показувати, як він підтримує твердження.')});
const h=safeGet('pp5_l2_hyp');if(h)$('#savedHyp').textContent='Ваша початкова гіпотеза: «'+h+'»';

function validFullName(value){const parts=value.trim().replace(/\s+/g,' ').split(' ');return parts.length>=2&&parts.every(p=>/^[А-ЯІЇЄҐа-яіїєґA-Za-z'’\-]+$/.test(p));}
const gate=$('#identityGate'), quiz=$('#quiz'), fullName=$('#fullName'), studentClass=$('#studentClass'), gateError=$('#gateError');
function openQuiz(){const name=fullName.value.trim().replace(/\s+/g,' '), cls=studentClass.value.trim();if(!validFullName(name)||!cls){showFeedback(gateError,'bad','Введіть ім’я, прізвище та клас. ПІБ має містити щонайменше два слова без цифр.');return false;}gateError.className='feedback bad';gate.hidden=true;quiz.hidden=false;quiz.classList.add('open');quiz.scrollIntoView({behavior:'smooth',block:'start'});document.body.dataset.quizOpened='true';return true;}
$('#startQuiz').addEventListener('click',openQuiz);

const exactSet=(name,arr)=>$$(`input[name="${name}"]:checked`).map(x=>x.value).sort().join('|')===arr.slice().sort().join('|');
function getScore(){let s=0;if($('input[name="q1"]:checked')?.value==='a')s++;if($('input[name="q2"]:checked')?.value==='c')s++;if($('input[name="q3"]:checked')?.value==='b')s++;if($('input[name="q4"]:checked')?.value==='a')s++;if(exactSet('q5',['a','b','d']))s++;if(exactSet('q6',['a','b','d']))s++;if($('#q7a').value==='hooks'&&$('#q7b').value==='water'&&$('#q7c').value==='adhesion'&&$('#q7d').value==='shape')s++;if($('#q8_1').value==='Б'&&$('#q8_2').value==='Г'&&$('#q8_3').value==='В'&&$('#q8_4').value==='А')s++;if($('input[name="q9"]:checked')?.value==='a')s++;if($('input[name="q10"]:checked')?.value==='c')s++;return s;}
function answeredCount(){let n=0;for(let i=1;i<=4;i++)if($(`input[name="q${i}"]:checked`))n++;if($$('input[name="q5"]:checked').length)n++;if($$('input[name="q6"]:checked').length)n++;if(['#q7a','#q7b','#q7c','#q7d'].every(s=>$(s).value))n++;if(['#q8_1','#q8_2','#q8_3','#q8_4'].every(s=>$(s).value))n++;if($('input[name="q9"]:checked'))n++;if($('input[name="q10"]:checked'))n++;return n;}
quiz.addEventListener('submit',e=>{e.preventDefault();const count=answeredCount();if(count<10){showFeedback($('#quizError'),'bad',`Заповніть усі 10 завдань. Зараз завершено: ${count}/10.`);return;}$('#quizError').className='feedback bad';const score=getScore(),pct=score*10;$('#scoreText').textContent=`${score}/10 • ${pct}%`;$('#resultName').textContent=fullName.value.trim();$('#resultClass').textContent=studentClass.value.trim();$('#resultTime').textContent=new Date().toLocaleString('uk-UA');$('#levelText').textContent=score<=4?'Потрібно повторити ключові поняття.':score<=7?'Достатній результат — перевірте помилки.':score<=9?'Добре — Ви впевнено розрізняєте відкриття, винахід і докази.':'Відмінно — 10/10.';$('#resultCard').classList.add('show');$('#resultCard').scrollIntoView({behavior:'smooth',block:'start'});document.body.dataset.quizScore=String(score)});
$('#resetQuiz').addEventListener('click',()=>{quiz.reset();$('#quizError').className='feedback bad'});$('#retryQuiz').addEventListener('click',()=>{quiz.reset();$('#resultCard').classList.remove('show');quiz.scrollIntoView({behavior:'smooth',block:'start'})});$('#printResult').addEventListener('click',()=>window.print());

function runSelfTest(){fullName.value='Тестова Учениця';studentClass.value='5-А';if(!openQuiz()){document.body.dataset.selftest='gate-failed';return;}const choose=(n,v)=>{const el=$(`input[name="q${n}"][value="${v}"]`);if(el)el.checked=true};choose(1,'a');choose(2,'c');choose(3,'b');choose(4,'a');['a','b','d'].forEach(v=>{const e=$(`input[name="q5"][value="${v}"]`);if(e)e.checked=true});['a','b','d'].forEach(v=>{const e=$(`input[name="q6"][value="${v}"]`);if(e)e.checked=true});$('#q7a').value='hooks';$('#q7b').value='water';$('#q7c').value='adhesion';$('#q7d').value='shape';$('#q8_1').value='Б';$('#q8_2').value='Г';$('#q8_3').value='В';$('#q8_4').value='А';choose(9,'a');choose(10,'c');quiz.requestSubmit();document.body.dataset.selftest=($('#resultCard').classList.contains('show')&&document.body.dataset.quizScore==='10'&&document.body.dataset.quizOpened==='true')?'pass':'fail';}
if(new URLSearchParams(location.search).get('selftest')==='1')setTimeout(runSelfTest,50);