const temps=[-3,-2,3,10,16,20,21,20,15,9,3,-1], months=['Січ','Лют','Бер','Кві','Тра','Чер','Лип','Сер','Вер','Жов','Лис','Гру'];
const grid=document.querySelector('#monthGrid');grid.innerHTML=months.map((m,i)=>`<div class="month"><span>${m}</span><b>${temps[i]}°</b></div>`).join('');

document.querySelectorAll('.city').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.city').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t={kyiv:'Київ: проміжний випадок — сезонність помітна, але не така різка, як у глибині материка.',london:'Лондон: океан повільніше нагрівається й охолоджується, тому зима м’якша, літо прохолодніше, амплітуда менша.',astana:'Астана: далекість від океану сприяє сильнішому зимовому охолодженню й літньому прогріванню — амплітуда найбільша.'};document.querySelector('#cityHint').textContent=t[b.dataset.city]}));

function draw(){const c=document.querySelector('#chart'),ctx=c.getContext('2d'),W=c.width,H=c.height,p=52;ctx.clearRect(0,0,W,H);ctx.fillStyle='#fbfdff';ctx.fillRect(0,0,W,H);const ymin=-5,ymax=25;const x=i=>p+i*(W-2*p)/11,y=v=>H-p-(v-ymin)*(H-2*p)/(ymax-ymin);ctx.strokeStyle='#dbe8ef';ctx.lineWidth=1;ctx.font='14px system-ui';ctx.fillStyle='#67808f';for(let v=-5;v<=25;v+=5){ctx.beginPath();ctx.moveTo(p,y(v));ctx.lineTo(W-p,y(v));ctx.stroke();ctx.fillText(v+'°',12,y(v)+5)}months.forEach((m,i)=>ctx.fillText(m,x(i)-12,H-18));ctx.strokeStyle='#0f7f69';ctx.lineWidth=5;ctx.beginPath();temps.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();temps.forEach((v,i)=>{ctx.beginPath();ctx.fillStyle='#fff';ctx.strokeStyle='#0f7f69';ctx.lineWidth=4;ctx.arc(x(i),y(v),6,0,Math.PI*2);ctx.fill();ctx.stroke()});document.querySelector('#chartMsg').textContent='Знайдіть найтепліший і найхолодніший місяці. Потім переходьте до обчислень.';document.querySelector('#chartMsg').className='feedback good'}
document.querySelector('#drawChart').addEventListener('click',draw);

const mean=temps.reduce((a,b)=>a+b,0)/12, amp=Math.max(...temps)-Math.min(...temps);
document.querySelectorAll('.check').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.kind==='mean'){const v=parseFloat(document.querySelector('#meanAns').value),o=document.querySelector('#meanOut');o.textContent=Math.abs(v-mean)<.11?`Так. (${temps.join(' + ')}) ÷ 12 = ${mean.toFixed(1)} °C.`:`Перевірте суму 12 значень і ділення на 12. Очікується число близько ${mean.toFixed(1)} °C.`;o.className='feedback '+(Math.abs(v-mean)<.11?'good':'bad')}else{const v=parseFloat(document.querySelector('#ampAns').value),o=document.querySelector('#ampOut');o.textContent=v===amp?`Так: 21 − (−3) = ${amp} °C.`:'Пам’ятайте: максимум 21 °C, мінімум −3 °C. Віднімайте число зі знаком.';o.className='feedback '+(v===amp?'good':'bad')}}));

document.querySelectorAll('.reveal').forEach(b=>b.addEventListener('click',()=>{b.textContent=b.dataset.answer+' °C';b.disabled=true}));
document.querySelector('#proofBtn').addEventListener('click',()=>{const s=document.querySelector('#proofText').value.toLowerCase(),o=document.querySelector('#proofOut'),score=['лондон','астан','14','35','океан','матер'].filter(k=>s.includes(k)).length;o.textContent=score>=4?'Структура доказу є: Ви використали порівняння даних і причинне пояснення. Перевірте, чи прямо сказали, що океан зменшує сезонні крайнощі.':'Посильте доказ: наведіть амплітуди (≈14 °C і ≈35 °C) та поясніть роль Атлантики й континентальності.';o.className='feedback '+(score>=4?'good':'bad')});

document.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',()=>{const box=b.closest('.activity'),out=box.querySelector('.feedback');box.querySelectorAll('[data-check]').forEach(x=>x.classList.remove('ok','no'));if(b.dataset.check==='right'){b.classList.add('ok');out.textContent='Правильно. Сезонність визначає геометрія освітлення через нахил осі, а не проста зміна відстані до Сонця.';out.className='feedback good'}else{b.classList.add('no');out.textContent='Ні. Це не пояснило б протилежні сезони у Північній і Південній півкулях.';out.className='feedback bad'}}));

document.querySelector('#cerBtn').addEventListener('click',()=>{const c=document.querySelector('#cerC').value,e=document.querySelector('#cerE').value,r=document.querySelector('#cerR').value,o=document.querySelector('#cerOut');const ok=c.length>18&&/14|35/.test(e)&&/океан|континент|вода|материк/i.test(r);o.textContent=ok?'CER має всі три частини: тезу, числовий доказ і механізм пояснення.':'Потрібні три різні речі: теза; числовий доказ (амплітуди); пояснення ролі океану/континентальності.';o.className='feedback '+(ok?'good':'bad')});

const questions=[
['Що називають річною амплітудою температури?',['Суму 12 температур','Різницю між найвищою і найнижчою температурою року','Середню температуру липня','Різницю між днем і ніччю'],1],
['Tmax = 22 °C, Tmin = −8 °C. Амплітуда дорівнює…',['14 °C','22 °C','30 °C','−30 °C'],2],
['Як у шкільній задачі знайти середню річну температуру за 12 середніми місячними?',['Скласти 12 значень і поділити на 12','Відняти мінімум від максимуму','Взяти лише січень і липень','Додати максимум і мінімум'],0],
['Головна причина сезонної зміни надходження сонячної енергії в помірних широтах…',['Зміна маси Землі','Нахил осі Землі та її рух навколо Сонця','Щоденна зміна погоди','Місячні фази'],1],
['Чому Лондон має меншу річну амплітуду, ніж Астана на близькій широті?',['Лондон ближче до Атлантики','Лондон ближче до екватора на 30°','Астана в іншій півкулі','Через різну тривалість року'],0],
['Який графік найкраще показує річний хід температури?',['Кругова діаграма країн','Лінійний графік: місяці по осі X, температура по Y','Карта корисних копалин','Роза вітрів'],1],
['Якщо середні місячні температури всі підвищилися на 2 °C, а їх різниця між Tmax і Tmin не змінилася, амплітуда…',['Зросте на 2 °C','Зменшиться на 2 °C','Не зміниться','Стане нульовою'],2],
['Яке твердження є доказом, а не лише поясненням?',['Океан впливає на клімат','У Лондоні амплітуда ≈14 °C, в Астані ≈35 °C','Континентальність важлива','Сезони змінюються'],1],
['Де за інших рівних умов сезонні контрасти часто більші?',['У глибині великого материка','На невеликому океанічному острові','Безпосередньо над океаном','Різниці не буває'],0],
['Для CER у частині Evidence потрібно…',['Повторити тезу іншими словами','Навести конкретні дані або спостереження','Написати лише висновок','Вказати своє ім’я'],1]
];
function renderQuiz(){const q=document.querySelector('#quiz');q.innerHTML=questions.map((x,i)=>`<div class="q"><h3>${i+1}. ${x[0]}</h3>${x[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('')+'<button type="submit" class="btn">Завершити тест</button>'}
document.querySelector('#unlock').addEventListener('click',()=>{const vals=['surname','name','klass'].map(id=>document.querySelector('#'+id).value.trim()),m=document.querySelector('#lockMsg');if(vals.every(Boolean)){renderQuiz();document.querySelector('#quiz').classList.remove('hidden');m.textContent=`Тест відкрито для: ${vals[0]} ${vals[1]}, ${vals[2]}.`;m.className='feedback good';document.querySelector('#quiz').scrollIntoView({behavior:'smooth',block:'start'})}else{m.textContent='Заповніть прізвище, ім’я та клас — усі три поля обов’язкові.';m.className='feedback bad'}});
document.querySelector('#quiz').addEventListener('submit',e=>{e.preventDefault();let score=0;questions.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q[2])score++});const r=document.querySelector('#result');r.classList.remove('hidden');r.innerHTML=`Результат: <b>${score}/10</b>. ${score>=8?'Тему опрацьовано впевнено.':score>=6?'Перегляньте помилки й повторіть формули середньої та амплітуди.':'Поверніться до графіка, обчислень і блоку про причини сезонності.'}`;r.scrollIntoView({behavior:'smooth'})});