(()=>{
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
// Warmup
$$('#multiChoices .choice').forEach(b=>b.addEventListener('click',()=>{b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')==='true'?'false':'true')}));
$('#checkWarm').addEventListener('click',()=>{const n=$$('#multiChoices .choice[aria-pressed="true"]').length;$('#warmFeedback').innerHTML=n>=3?'Так. <b>Більшість сучасних професій можна описувати через кілька сфер.</b> Далі перевіримо це не інтуїцією, а через задачі та інструменти.':'Спробуйте вибрати ще. Майже кожен приклад тут має щонайменше <b>дві сильні складові</b>.'});
// Classifier
const spheres={people:'Люди й добробут',tech:'Технології й дані',eng:'Інженерія й виробництво',business:'Бізнес і організація',creative:'Творчість і комунікація',nature:'Природа й середовище'};
const jobs=[
{name:'UX-дизайнер',main:'creative',second:'tech',why:'Проєктує досвід користувача: творчість + цифрові інструменти + дослідження людей.'},
{name:'Біоінформатик',main:'tech',second:'nature',why:'Аналізує біологічні дані методами програмування й статистики.'},
{name:'Медична сестра',main:'people',second:null,why:'Основний об’єкт праці — здоров’я й догляд за людьми.'},
{name:'Інженер-енергетик',main:'eng',second:'tech',why:'Проєктує й експлуатує технічні енергетичні системи, часто з цифровим керуванням.'},
{name:'Агроном',main:'nature',second:'business',why:'Працює з рослинами, ґрунтами й технологіями вирощування; у виробництві також приймає економічні рішення.'},
{name:'SMM-менеджер',main:'creative',second:'business',why:'Створює комунікацію та контент для бізнесових цілей.'},
{name:'Логіст',main:'business',second:'tech',why:'Організовує потоки товарів і даних, дедалі частіше працює з цифровими системами.'},
{name:'Кар’єрний радник',main:'people',second:'business',why:'Працює з людьми, але аналізує освіту, професії й ринок праці.'},
{name:'Еколог-аналітик',main:'nature',second:'tech',why:'Досліджує довкілля й працює з даними, моделями та картами.'}
];
let selectedJob=null;
const bank=$('#professionBank');jobs.forEach((j,i)=>{const b=document.createElement('button');b.className='profession-chip';b.textContent=j.name;b.dataset.i=i;b.addEventListener('click',()=>{selectedJob=j;$$('.profession-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#labPrompt').innerHTML=`Обрано: <b>${j.name}</b>. Тепер визначте основну сферу.`});bank.appendChild(b)});
const dz=$('#dropzones');Object.entries(spheres).forEach(([k,v])=>{const b=document.createElement('button');b.className='dropzone';b.innerHTML=`<strong>${v}</strong><span class="mini">обрати як основну</span>`;b.addEventListener('click',()=>{if(!selectedJob){$('#labFeedback').textContent='Спочатку оберіть професію з банку.';return}const ok=k===selectedJob.main;$('#labFeedback').innerHTML=ok?`✅ <b>${selectedJob.name}</b>: сильна основна сфера — <b>${spheres[selectedJob.main]}</b>${selectedJob.second?`, але є виразна друга — <b>${spheres[selectedJob.second]}</b>`:''}. ${selectedJob.why}`:`Спробуйте ще раз. Для цієї навчальної моделі сильніший центр — <b>${spheres[selectedJob.main]}</b>. ${selectedJob.why}`});dz.appendChild(b)});
// Passports
const passports=[
{name:'UX-дизайнер',tasks:'досліджує потреби, будує сценарії, проєктує інтерфейс',object:'люди + цифровий продукт',tools:'прототипи, макети, аналітика, інтерв’ю',result:'зручніший досвід користувача',sphere:'Творчість + технології + люди'},
{name:'Ветеринарний лікар',tasks:'діагностує, лікує, консультує',object:'тварини + їхні власники',tools:'медичні знання, діагностика, комунікація',result:'здоров’я тварини й зрозумілий план догляду',sphere:'Люди й добробут + природа'},
{name:'Еколог-аналітик',tasks:'збирає й аналізує дані про стан довкілля',object:'екосистеми, показники, території',tools:'ГІС, таблиці, моделі, польові дані',result:'оцінка стану, ризику або рекомендація',sphere:'Природа + технології й дані'},
{name:'Інженер робототехніки',tasks:'проєктує, збирає, програмує й тестує системи',object:'механізми + електроніка + код',tools:'CAD, сенсори, контролери, програмування',result:'працездатна автоматизована система',sphere:'Інженерія + технології'}
];
const pb=$('#passportButtons');passports.forEach((p,i)=>{const b=document.createElement('button');b.className='btn ghost';b.textContent=p.name;b.addEventListener('click',()=>{ $('#passportTitle').textContent=p.name;$('#pTasks').textContent=p.tasks;$('#pObject').textContent=p.object;$('#pTools').textContent=p.tools;$('#pResult').textContent=p.result;$('#pSphere').innerHTML=`Навчальний висновок: <b>${p.sphere}</b>. Саме через задачі видно гібридність краще, ніж через назву.`});pb.appendChild(b)});
// Interest profile
const interestItems=[
['Пояснювати, підтримувати, навчати інших','people'],['Працювати з кодом, даними або цифровими системами','tech'],['Збирати, ремонтувати, конструювати речі','eng'],['Організовувати людей, ресурси чи процеси','business'],['Створювати візуальні, текстові або медійні продукти','creative'],['Досліджувати живі системи, природу або довкілля','nature'],['Розв’язувати конфлікти й допомагати приймати рішення','people'],['Шукати закономірності у великих масивах інформації','tech'],['Планувати маршрут, бюджет або постачання','business'],['Експериментувати з матеріалами, механізмами, інструментами','eng'],['Вигадувати образ, історію, стиль або спосіб подачі','creative'],['Спостерігати природні процеси й працювати «в полі»','nature']
];
interestItems.forEach(([t,s],i)=>{const l=document.createElement('label');l.className='check';l.innerHTML=`<input type="checkbox" data-sphere="${s}"><span>${t}</span>`;$('#interestList').appendChild(l)});
Object.entries(spheres).forEach(([k,v])=>{const d=document.createElement('div');d.style.marginBottom='.75rem';d.innerHTML=`<div style="display:flex;justify-content:space-between;gap:.5rem"><b>${v}</b><span id="mval-${k}" class="mini">0/2</span></div><div class="meter"><span id="meter-${k}"></span></div>`;$('#meters').appendChild(d)});
$('#buildInterest').addEventListener('click',()=>{const score={people:0,tech:0,eng:0,business:0,creative:0,nature:0};$$('#interestList input:checked').forEach(x=>score[x.dataset.sphere]++);Object.keys(score).forEach(k=>{$(`#mval-${k}`).textContent=`${score[k]}/2`;$(`#meter-${k}`).style.width=`${score[k]*50}%`});const sorted=Object.entries(score).sort((a,b)=>b[1]-a[1]);const best=sorted.filter(x=>x[1]===sorted[0][1]&&x[1]>0).map(x=>spheres[x[0]]);const box=$('#interestResult');box.classList.add('show');box.innerHTML=best.length?`Найсильніші сигнали зараз: <b>${best.join(' • ')}</b>. Це не «вирок професії» — оберіть 2–3 професії з цих сфер і перевірте їх через професійний паспорт.`:'Позначте хоча б 2–3 види діяльності, які Вам реально подобаються.'});
// Myths
const mythData=[['«Якщо професія належить до сфери технологій, у ній немає творчості».',false,'Ні. Розробка продуктів, інженерія, аналітика й програмування часто потребують пошуку нестандартних рішень.'],['«Класифікація корисна, якщо ми пам’ятаємо, для якої мети її створили».',true,'Так. Для профорієнтації карта сфер допомагає порівнювати діяльність; для офіційних назв робіт існує нормативний класифікатор.'],['«Один інтерес одразу визначає одну професію».',false,'Ні. Один вид діяльності може реалізовуватися в десятках професій і сфер. Потрібні додаткові дані й проби.']];
mythData.forEach(([t,truth,ex],i)=>{const d=document.createElement('div');d.className='myth';d.innerHTML=`<div><b>${t}</b><div class="mini" id="myth-f-${i}">Оберіть.</div></div><div class="myth-actions"><button class="btn ghost" data-v="1">Так</button><button class="btn ghost" data-v="0">Ні</button></div>`;$$('button',d).forEach(b=>b.addEventListener('click',()=>{$(`#myth-f-${i}`).innerHTML=(b.dataset.v==='1')===truth?`✅ ${ex}`:`↩️ ${ex}`}));$('#myths').appendChild(d)});
// CER persistence
const cerIds=['cerClaim','cerEvidence','cerReason'];cerIds.forEach(id=>{const v=localStorage.getItem('prof8_l2_'+id);if(v)$('#'+id).value=v});$('#saveCer').addEventListener('click',()=>{cerIds.forEach(id=>localStorage.setItem('prof8_l2_'+id,$('#'+id).value));$('#cerFeedback').innerHTML='✅ CER збережено локально на цьому пристрої.'});
// Quiz gate + score
function validFullName(v){const parts=v.trim().replace(/\s+/g,' ').split(' ');return parts.length>=2&&parts.every(p=>/^[А-ЯІЇЄҐа-яіїєґA-Za-z'’\-]+$/.test(p))}
$('#startQuiz').addEventListener('click',()=>{if(!validFullName($('#fullName').value)||!$('#studentClass').value){$('#gateError').textContent='Введіть ім’я, прізвище та клас.';return}$('#gateError').textContent='';$('#identityGate').style.display='none';$('#quiz').classList.add('open');$('#quiz').scrollIntoView({behavior:'smooth',block:'start'})});
function exact(name,vals){const got=$$(`input[name="${name}"]:checked`).map(x=>x.value).sort().join('|');return got===[...vals].sort().join('|')}
$('#submitQuiz').addEventListener('click',()=>{let s=0;if($('input[name="q1"]:checked')?.value==='b')s++;if($('input[name="q2"]:checked')?.value==='a')s++;if($('input[name="q3"]:checked')?.value==='b')s++;if($('input[name="q4"]:checked')?.value==='b')s++;if(exact('q5',['bio','ux','eco']))s++;if(exact('q6',['purpose','hybrid','official']))s++;if($('[name="q7a"]').value==='people'&&$('[name="q7b"]').value==='tech'&&$('[name="q7c"]').value==='eng'&&$('[name="q7d"]').value==='nature')s++;if($('[name="q8"]').value==='b')s++;if($('input[name="q9"]:checked')?.value==='a')s++;if($('input[name="q10"]:checked')?.value==='b')s++;const pct=s*10;const comment=s<=4?'Потрібно ще раз пройти різницю між професією, сферою та професійним паспортом.':s<=7?'Достатньо: основна логіка зрозуміла, але зверніть увагу на гібридні професії та мету класифікації.':s<=9?'Добре: Ви впевнено аналізуєте професії за задачами й сферами.':'Відмінно: Ви коректно працюєте з гібридністю професій і межами класифікації.';$('#scoreText').textContent=`${s}/10`;$('#resultName').textContent=$('#fullName').value.trim();$('#resultClass').textContent=$('#studentClass').value;$('#resultPercent').textContent=pct+'%';$('#resultTime').textContent=new Date().toLocaleString('uk-UA');$('#resultComment').textContent=comment;$('#resultCard').classList.add('show');$('#resultCard').scrollIntoView({behavior:'smooth',block:'center'})});
$('#printResult').addEventListener('click',()=>window.print());$('#retryQuiz').addEventListener('click',()=>{if(confirm('Очистити відповіді тесту? Ім’я та клас залишаться.')){$('#quiz').reset();$('#resultCard').classList.remove('show');$('#quiz').scrollIntoView({behavior:'smooth'})}});
})();