const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$$('.answers').forEach(box=>{box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('good','bad'));const ok=b.dataset.v===box.dataset.correct;b.classList.add(ok?'good':'bad');box.nextElementSibling.textContent=ok?'Так. Підземна вода зазвичай міститься у порах і тріщинах порід.':'Спробуйте ще: шукайте не обов’язково порожню печеру, а насичені водою пори й тріщини.'})});
const perm={gravel:{name:'гравій',k:.9,text:'Великі сполучені пори → вода проходить швидко.'},sand:{name:'пісок',k:.7,text:'Пори менші, але добре сполучені → вода проходить досить легко.'},clay:{name:'глина',k:.12,text:'Дрібні пори й низька проникність → вода рухається дуже повільно.'},fractured:{name:'тріщинуватий вапняк',k:.82,text:'Тріщини та карстові канали можуть проводити воду дуже швидко.'}};
function updatePerm(){const m=$('#material').value,r=+$('#rain').value,p=perm[m];$('#rainV').textContent=r;$('#ground').className='ground '+m;const h=Math.min(55,8+r*p.k*.45);$('#waterFill').style.height=h+'%';$('#permOut').innerHTML=`<b>${p.name}:</b> ${p.text} За однакових опадів умовна інфільтрація тут ${p.k>.75?'висока':p.k>.4?'середня':'низька'}.`;}
$('#material').onchange=updatePerm;$('#rain').oninput=updatePerm;updatePerm();
function updateAquifer(){const r=+$('#recharge').value,p=+$('#pump').value,w=+$('#well').value;$('#rechargeV').textContent=r;$('#pumpV').textContent=p;$('#wellV').textContent=w;const waterTable=Math.max(8,34+(p-r)*.28);const hits=w>waterTable;$('#aquiferOut').innerHTML=`Умовна глибина рівня води: <b>${waterTable.toFixed(1)} м</b>. Свердловина ${hits?'<b>досягає</b> насиченої зони':'<b>не досягає</b> насиченої зони'}. ${p>r?'Відкачування переважає поповнення — рівень знижується.':'Поповнення не менше за відкачування — рівень стабільніший.'}`;}
['recharge','pump','well'].forEach(id=>$('#'+id).oninput=updateAquifer);updateAquifer();
$('#checkLayer').onclick=()=>{$('#layerOut').textContent=$('#layerAns').value==='21-38'?'Правильно: насичений водою пісок — найкращий кандидат на водоносний горизонт.':'Перевірте ознаки: шар має бути проникним і насиченим водою.'};
$('#proofLayer').onclick=()=>{const t=$('#layerProof').value.toLowerCase();const ok=(t.includes('піс')||t.includes('проник'))&&(t.includes('вода')||t.includes('насич'))&&(t.includes('глин')||t.includes('водотр'));$('#proofLayerOut').textContent=ok?'Структура доказу є: властивість породи + насичення + роль сусіднього шару.':'Додайте три елементи: проникність породи, факт насичення водою та роль глини/водотривкого шару.'};
let map=L.map('map').setView([48.7,24.1],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);let marker=L.marker([49.278,23.506]).addTo(map).bindPopup('Трускавець — мінеральні води');$$('.place').forEach(b=>b.onclick=()=>{const lat=+b.dataset.lat,lon=+b.dataset.lon,z=+b.dataset.z;map.setView([lat,lon],z);marker.setLatLng([lat,lon]).bindPopup(b.textContent).openPopup()});
function updateMineral(){const rock=$('#rock').value,t=+$('#contact').value;$('#timeV').textContent=t;const base={limestone:1.0,salt:2.0,granite:.45}[rock];const score=Math.min(100,Math.round(t*base));const txt=score>70?'висока':score>35?'середня':'низька';$('#mineralOut').innerHTML=`Умовна здатність води набувати розчинених речовин: <b>${txt}</b> (${score}/100). Це не прогноз реального складу, а модель ролі породи й часу контакту.`;}
$('#rock').onchange=updateMineral;$('#contact').oninput=updateMineral;updateMineral();
function updateThermal(){const d=+$('#depth').value,g=+$('#gradient').value;$('#depthV').textContent=d.toFixed(1);const t=10+d*g;$('#thermalOut').innerHTML=`Спрощена оцінка температури на глибині: <b>≈ ${t.toFixed(0)} °C</b> (старт 10 °C + глибина × градієнт). Реальна температура залежить від місцевої геології.`;}
$('#depth').oninput=updateThermal;$('#gradient').onchange=updateThermal;updateThermal();
$('#cerCheck').onclick=()=>{const c=$('#cerC').value.trim(),e=$('#cerE').value.trim(),r=$('#cerR').value.trim();$('#cerOut').textContent=c.length>15&&e.length>25&&r.length>25?'CER структуровано: є теза, докази й пояснення причинного зв’язку.':'Посильте відповідь: окрема теза, конкретні докази з уроку та пояснення, чому вони підтримують тезу.'};
const qs=[
['Підземні води найчастіше містяться…',['у порах і тріщинах порід','лише у великих печерах','тільки під океанами'],0],
['Верхня межа насиченої водою зони — це…',['вододіл','рівень ґрунтових вод','русло'],1],
['Яка порода зазвичай найкраще пропускає воду?',['пісок','щільна глина','суцільний граніт без тріщин'],0],
['Водоносний горизонт — це…',['проникний шар, що зберігає і передає воду','будь-який сухий шар','лише підземна печера'],0],
['Що поповнює підземні води?',['інфільтрація опадів','лише випаровування','тільки вітер'],0],
['Якщо відкачування довго перевищує поповнення, рівень води…',['зростає','не змінюється ніколи','може знижуватися'],2],
['Мінеральний склад підземної води залежить насамперед від…',['контакту з породами та умов руху','кольору неба','фази Місяця'],0],
['Термальні води мають підвищену температуру через…',['тепло надр Землі','лише сонячне світло','морські припливи'],0],
['Джерело — це місце, де…',['підземна вода виходить на поверхню','річка завжди впадає в море','утворюється хмара'],0],
['Чому вода з двох свердловин може відрізнятися?',['через різні шари, глибину й шлях води','це неможливо','лише через форму відра'],0]
];
function renderQuiz(){const q=$('#quiz');q.innerHTML=qs.map((x,i)=>`<div class="quizq"><b>${i+1}. ${x[0]}</b>${x[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('')+'<button type="submit">Завершити тест</button>';q.onsubmit=e=>{e.preventDefault();let s=0;qs.forEach((x,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===x[2])s++});$('#score').classList.remove('hidden');$('#score').textContent=`Результат: ${s}/10. ${s>=8?'Сильне розуміння моделі підземних вод.':s>=6?'Основу засвоєно; перегляньте помилки.':'Поверніться до моделей проникності, водоносного горизонту й джерел.'}`;};}
$('#unlock').onclick=()=>{const ok=$('#surname').value.trim()&&$('#name').value.trim()&&$('#klass').value;if(!ok){$('#gateMsg').textContent='Заповніть прізвище, ім’я та клас.';return}$('#gateMsg').textContent='Тест відкрито.';$('#quiz').classList.remove('hidden');renderQuiz();};