const safetyFb=document.getElementById('safetyFb'),scaleFb=document.getElementById('scaleFb'),tempBig=document.getElementById('tempBig'),mercury=document.getElementById('mercury'),mistakeFb=document.getElementById('mistakeFb'),airT=document.getElementById('airT'),waterT=document.getElementById('waterT'),airVal=document.getElementById('airVal'),waterVal=document.getElementById('waterVal'),airBar=document.getElementById('airBar'),waterBar=document.getElementById('waterBar'),labFb=document.getElementById('labFb'),conclusion=document.getElementById('conclusion'),gate=document.getElementById('gate'),gateErr=document.getElementById('gateErr'),quiz=document.getElementById('quiz'),result=document.getElementById('result'),fullName=document.getElementById('fullName'),studentClass=document.getElementById('studentClass');
const safety=[...document.querySelectorAll('.safety')];safety.forEach(x=>x.addEventListener('click',()=>x.classList.toggle('selected')));function checkSafety(){let c=0;safety.forEach(x=>{x.classList.remove('wrong');const p=x.classList.contains('selected'),g=x.dataset.good==='1';if(p===g)c++;else x.classList.add('wrong')});safetyFb.textContent=c===safety.length?'Так. Можна переходити до вимірювань.':'Перевірте картки ще раз: безпека важливіша за красиві цифри.'}
function scaleAnswer(v){scaleFb.textContent=v===2.5?'Правильно: (30−20) / 4 = 2,5 °C на один проміжок.':'Ще раз: між 20 і 30 тут чотири однакові проміжки.'}
const tempSlider=document.getElementById('tempSlider');function updateThermo(){const v=+tempSlider.value;tempBig.textContent=v+' °C';mercury.style.height=(8+v/40*84)+'%'}tempSlider.addEventListener('input',updateThermo);updateThermo();
const mistakes=[...document.querySelectorAll('.mistake')];mistakes.forEach(m=>m.addEventListener('click',()=>{mistakes.forEach(x=>x.classList.remove('selected','bad'));if(m.dataset.good==='1'){m.classList.add('selected');mistakeFb.textContent='Так. Чутлива частина у воді, але не торкається посудини.'}else{m.classList.add('bad');mistakeFb.textContent='Є проблема: прилад може показати температуру посудини або взагалі не вимірювати воду правильно.'}}));
function analyzeLab(){const a=+airT.value,w=+waterT.value;if(!Number.isFinite(a)||!Number.isFinite(w)||airT.value===''||waterT.value===''){labFb.textContent='Введіть обидва виміряні значення.';return}const diff=Math.abs(a-w);airVal.textContent=a+' °C';waterVal.textContent=w+' °C';const scale=Math.max(40,a,w,1);airBar.style.height=Math.max(12,a/scale*190)+'px';waterBar.style.height=Math.max(12,w/scale*190)+'px';const warmer=a>w?'повітря':w>a?'вода':'температури однакові';labFb.textContent=a===w?`За Вашими даними температури однакові: ${a} °C.`:`За Вашими даними тепліше: ${warmer}. Різниця ${diff.toFixed(1).replace('.0','')} °C.`;conclusion.value=a===w?`Температура повітря і води в моєму вимірюванні була однаковою — ${a} °C. Для надійності результат можна повторити.`:`Температура ${warmer} була вищою. Різниця між температурою повітря (${a} °C) і води (${w} °C) становила ${diff.toFixed(1).replace('.0','')} °C. Результат залежить від умов вимірювання.`}
const questions=[
['Що вимірює термометр?',['Масу','Температуру','Об’єм','Час'],1],
['Яка одиниця температури використовується в нашій практичній?',['метр','градус Цельсія','літр','грам'],1],
['Що треба зробити перед точним зчитуванням показу?',['Одразу записати перше число','Дочекатися стабілізації показу','Потррсти термометр у воді','Тримати колбу пальцями'],1],
['Як правильно розмістити чутливу частину термометра у воді?',['Притиснути до дна','Притиснути до стінки','Занурити у воду, не торкаючись дна і стінок','Тримати над водою'],2],
['Між 10 °C і 20 °C п’ять однакових проміжків. Ціна поділки…',['1 °C','2 °C','5 °C','10 °C'],1],
['Чому не варто тримати чутливу частину термометра рукою?',['Рука може змінити температуру, яку вимірюємо','Термометр стане важчим','Зникнуть поділки','Зміниться одиниця'],0],
['Який висновок кращий?',['Вода була нормальна','Вода 18 °C, повітря 22 °C; повітря тепліше на 4 °C','Все виміряли','Термометр працює'],1],
['Що може спотворити вимірювання повітря?',['Близькість батареї або прямого сонця','Запис у таблицю','Одиниця °C','Спокійне очікування'],0],
['Чому ми записуємо умови вимірювання?',['Щоб таблиця була довша','Щоб розуміти, що могло вплинути на результат','Бо так красивіше','Це не потрібно'],1],
['Що робити з дуже гарячою водою в цій практичній?',['Брати руками','Не використовувати без спеціальної вказівки вчителя','Пити після вимірювання','Ставити на край парти'],1]];
function validName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(x))}function openQuiz(){gateErr.textContent='';if(!validName(fullName.value)||!studentClass.value.trim()){gateErr.textContent='Введіть ім’я, прізвище та клас.';return}gate.classList.add('hidden');quiz.classList.add('open');quiz.innerHTML=questions.map((q,i)=>`<fieldset class="q"><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</fieldset>`).join('')+'<button type="submit">Завершити тест</button>'}
function submitQuiz(e){e.preventDefault();let s=0;questions.forEach((q,i)=>{const a=quiz.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q[2])s++});const pct=s*10;const c=s<=4?'Повторіть правила безпеки, шкалу й алгоритм вимірювання.':s<=7?'Добре: основний алгоритм уже тримається.':s<=9?'Дуже добре: Ви вмієте не лише читати число, а й оцінювати умови.':'10/10 — термометр задоволений, дані теж.';const now=new Date().toLocaleString('uk-UA');result.innerHTML=`<div class="resultCard"><div class="big">${s}/10 • ${pct}%</div><b>${fullName.value} • ${studentClass.value}</b><p>${c}</p><p class="tiny">${now}</p><b>Зробіть скриншот цієї картки й надішліть учителю.</b></div>`;result.scrollIntoView({behavior:'smooth'});return false}