const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const dataIntro=$('#data > p');if(dataIntro)dataIntro.innerHTML='Copernicus повідомляє: у 2025 році глобальна концентрація CO₂ становила близько <b>425,6 ppm</b>, що на <b>15,6 ppm</b> більше, ніж у 2019 році. Обчисліть приблизну концентрацію CO₂ у 2019 році.';
$$('.choice-row').forEach(row=>row.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;const ok=e.target.dataset.v===row.dataset.answer;row.nextElementSibling.textContent=ok?'✓ Саме так. Один локальний кадр не доводить глобальну тенденцію: потрібні довгі ряди незалежних спостережень.':'Не зовсім. Зображення показує конкретне явище в певний момент; кліматичний висновок потребує багаторічних даних.';}));
$$('.reveal').forEach(b=>b.onclick=()=>{const x=document.getElementById(b.dataset.target);x.hidden=!x.hidden});
const ghg=$('#ghg'),ghgOut=$('#ghgOut'),heatBar=$('#heatBar'),heatText=$('#heatText');function updateGHG(){const v=+ghg.value;ghgOut.value=v;heatBar.style.width=(20+v*.72)+'%';heatText.textContent=v<25?'Модель: додаткове утримання тепла невелике. Природний парниковий ефект усе одно існує.':v<65?'Модель: зі збільшенням кількості парникових газів більша частка теплової енергії затримується в системі.':'Модель: сильніше посилення парникового ефекту → більший дисбаланс енергії. Це не означає однакове потепління всюди.'}ghg.oninput=updateGHG;updateGHG();
const mixIds=['coal','gas','solar','wind'];function updateMix(){const vals=Object.fromEntries(mixIds.map(id=>[id,+$('#'+id).value]));mixIds.forEach(id=>$('#'+id).nextElementSibling.value=vals[id]);const sum=Object.values(vals).reduce((a,b)=>a+b,0);$('#sumMix').textContent=sum+'%';const fp=Math.round((vals.coal*4+vals.gas*2+vals.solar*.25+vals.wind*.2)/Math.max(sum,1)*25);$('#footprint').textContent=sum===100?fp+' / 100':'спочатку 100%';const active=Object.values(vals).filter(v=>v>=10).length;$('#diversity').textContent=active>=3?'висока':active===2?'середня':'низька';$('#mixAdvice').textContent=sum!==100?'Відрегулюйте повзунки: сумарно має бути 100%.':fp<35?'Ваш модельний мікс має низький відносний слід. Тепер поясніть, як громада балансуватиме змінність сонця й вітру.':fp<65?'Компромісний мікс. Спробуйте зменшити частку джерел із більшим модельним слідом, не забуваючи про надійність системи.':'Високий модельний слід. Чи можна частину виробництва перенести на низьковуглецеві джерела?'}mixIds.forEach(id=>$('#'+id).oninput=updateMix);updateMix();
$('#checkCo2').onclick=()=>{const v=parseFloat($('#co2Answer').value),target=410.0;$('#co2Feedback').textContent=Number.isFinite(v)&&Math.abs(v-target)<.11?'✓ 425,6 − 15,6 ≈ 410,0 ppm у 2019 році. Це оцінка концентрації, виведена з даних Copernicus.':'Підказка: від 425,6 ppm відніміть зростання 15,6 ppm.'};
const labels={data:'ДАНІ / СПОСТЕРЕЖЕННЯ',claim:'ВИСНОВОК / ТВЕРДЖЕННЯ',mechanism:'МЕХАНІЗМ'};$$('.evidence').forEach(b=>b.onclick=()=>{b.classList.add('marked');$('#sortResult').textContent='«'+b.textContent+'» → '+labels[b.dataset.kind]+'. Щоб твердження було сильним, поєднуйте дані з поясненим механізмом.'});
$('#farmCheck').onclick=()=>{const v=document.querySelector('input[name=farm]:checked');$('#farmFeedback').textContent=!v?'Спочатку оберіть варіант.':v.value==='b'?'✓ Найкращий підхід: виміряти місцеві умови й потреби, а вже потім добирати технології.':'Це рішення робить висновок без достатніх даних. Поверніться до умови й запитайте: що треба виміряти перед вибором технології?'};
$('#cerCheck').onclick=()=>{const a=$('#cerC').value.trim(),b=$('#cerE').value.trim(),c=$('#cerR').value.trim();$('#cerFeedback').textContent=a.length>20&&b.length>45&&c.length>45?'✓ Структура CER заповнена. Перечитайте: чи докази справді підтримують саме Ваше твердження?':'Додайте зміст: C — чітке твердження; E — щонайменше два конкретні докази; R — зв’язок між ними.'};
const quizData=[
['Яке твердження про природний парниковий ефект правильне?',['Він потрібний для підтримання придатної для життя температури','Його не існувало до промислової революції','Він виникає лише в теплицях'],0],
['Що найкраще доводить довготривалу зміну клімату?',['Один спекотний день','Багаторічні ряди вимірювань із різних джерел','Одна фотографія хмари'],1],
['Яка людська діяльність прямо додає CO₂ в атмосферу?',['Спалювання вугілля, нафти й газу','Вимірювання температури','Спостереження за хмарами'],0],
['Чому сонячну станцію не ставлять навмання?',['Потрібно оцінити сонячний ресурс, площу й мережу','Сонце світить лише біля екватора','Панелі працюють тільки взимку'],0],
['Що слід зробити перед вибором місця для вітротурбіни?',['Виміряти або проаналізувати вітровий ресурс','Обрати найнижчу точку без даних','Орієнтуватися лише на колір карти'],0],
['Якщо 425,6 ppm у 2025 році — це на 15,6 ppm більше, ніж у 2019, то приблизне значення 2019 року…',['410,0 ppm','441,2 ppm','15,6 ppm'],0],
['Чому окремий димовий шлейф не є сам по собі доказом глобального потепління?',['Це локальне короткочасне спостереження','Дим ніколи не впливає на атмосферу','Супутники не бачать дим'],0],
['Що в CER означає E?',['Evidence — докази','Energy — енергія','Estimate — оцінка'],0],
['Яке рішення найкраще відповідає доказовому підходу?',['Спочатку зібрати місцеві дані, потім обрати технологію','Спочатку купити обладнання, потім дізнатися умови','Копіювати рішення іншого міста без перевірки'],0],
['Яке формулювання найточніше?',['Люди можуть впливати на склад атмосфери й кліматичну систему','Люди керують усією погодою','Будь-яка зміна погоди спричинена людиною'],0]
];
function renderQuiz(){const q=$('#quiz');q.innerHTML=quizData.map((x,i)=>`<fieldset class="quiz-q"><p>${i+1}. ${x[0]}</p>${x[1].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('')}</fieldset>`).join('')+'<button type="submit">Завершити тест</button>';q.hidden=false}
$('#unlock').onclick=()=>{const fields=[$('#surname'),$('#name'),$('#klass')];if(fields.some(x=>x.value.trim().length<2)){ $('#gateMsg').textContent='Заповніть прізвище, ім’я та клас.';return }$('#gateMsg').textContent='Тест відкрито для: '+fields.map(x=>x.value.trim()).join(' • ');renderQuiz()};
$('#quiz').addEventListener('submit',e=>{e.preventDefault();let score=0;quizData.forEach((x,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===x[2])score++});const box=$('#scoreBox');box.hidden=false;box.innerHTML=`${$('#surname').value} ${$('#name').value}, ${$('#klass').value}: <b>${score}/10</b>. ${score>=9?'Високий результат.':score>=7?'Основні зв’язки засвоєні.':score>=5?'Перегляньте теорію й доказові завдання.':'Поверніться до моделей і повторіть причинні зв’язки.'}`;box.scrollIntoView({behavior:'smooth',block:'center'})});