const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const routeBtn=$('#routeBtn'),routeOut=$('#routeOut');routeBtn.addEventListener('click',()=>{const v=document.querySelector('input[name="weak"]:checked')?.value;if(!v){routeOut.textContent='Спочатку оберіть тип труднощів.';return}const names={source:'A — Обрати джерело',direction:'B — Напрям і азимут',scale:'C — Масштаб',legend:'D — Легенда'};routeOut.textContent=`Почніть зі станції ${names[v]}, потім пройдіть решту.`;document.getElementById(v).scrollIntoView({behavior:'smooth',block:'center'})});
$$('[data-check]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.check;let ok=false,msg='';if(t==='source'){ok=$('#sourceSelect').value==='серія супутникових знімків різних років';msg=ok?'Так: серія знімків дає змогу порівнювати стан у різні роки.':'Потрібне джерело, яке фіксує реальний стан території у різні моменти часу.'}if(t==='direction'){ok=document.querySelector('input[name="az"]:checked')?.value==='90';msg=ok?'Так: схід відповідає 90°.':'Пригадайте: Пн 0°/360°, Сх 90°, Пд 180°, Зх 270°.'}if(t==='scale'){ok=Math.abs(Number($('#scaleAns').value)-10.5)<.01;msg=ok?'Так: 1 см = 2,5 км; 4,2 см = 10,5 км.':'Перетворіть 250 000 см у 2,5 км, а потім помножте на 4,2.'}if(t==='legend'){ok=document.querySelector('input[name="lg"]:checked')?.value==='no';msg=ok?'Так: колір кодує значення показника, а не площу території.':'Ні. Площа регіону та значення показника — різні властивості.'}const fb=$('#'+t+'Fb');fb.textContent=msg;fb.className='feedback '+(ok?'ok':'bad')}));
const fields=['#first','#last','#class'].map($);function gate(){const ok=fields.every(x=>x.value.trim().length>=2);$('#startTest').disabled=!ok}fields.forEach(x=>x.addEventListener('input',gate));
const questions=[
['Яке джерело найкраще для порівняння площі льодовика у 2000 і 2025 роках?',['глобус','серія супутникових знімків','політична карта','план міста'],1],
['Азимут на захід дорівнює…',['0°','90°','180°','270°'],3],
['На карті 5 см у масштабі 1:100 000. Реальна відстань:',['500 м','5 км','50 км','500 км'],1],
['Що пояснює значення кольорів і символів карти?',['масштаб','легенда','рамка','назва'],1],
['Яка карта має більший масштаб?',['1:10 000','1:100 000','1:1 000 000','1:10 000 000'],0],
['Для вимірювання звивистої лінії річки найдоречніше:',['транспортир','нитка або курвіметр','компас','термометр'],1],
['Темніший колір на картограмі завжди означає більшу площу території.',['так','ні'],1],
['Для актуального стану дорожньої мережі найдоречніше використати:',['давній шкільний атлас','актуальну цифрову карту','глобус','контурну карту'],1],
['Якщо знаменник числового масштабу зростає, масштаб стає…',['більшим','дрібнішим','незмінним','лінійним'],1],
['Надійний географічний висновок краще робити…',['за одним випадковим зображенням','порівнюючи доречні джерела й докази','лише за кольором карти','без перевірки легенди'],1]
];
function renderQuiz(){const q=$('#quiz');q.innerHTML=questions.map((x,i)=>`<div class="q"><b>${i+1}. ${x[0]}</b><div class="choices">${x[1].map((a,j)=>`<label class="choice"><input type="radio" name="q${i}" value="${j}">${a}</label>`).join('')}</div></div>`).join('');q.addEventListener('change',progress)}function progress(){const done=questions.filter((_,i)=>document.querySelector(`input[name="q${i}"]:checked`)).length;$('#bar').style.width=`${done*10}%`}
$('#startTest').addEventListener('click',()=>{$('#test').classList.remove('hidden');renderQuiz();$('#test').scrollIntoView({behavior:'smooth'})});
$('#finish').addEventListener('click',()=>{let score=0;questions.forEach((x,i)=>{const v=document.querySelector(`input[name="q${i}"]:checked`);if(v&&Number(v.value)===x[2])score++});const student=`${$('#first').value.trim()} ${$('#last').value.trim()}, ${$('#class').value.trim()}`;$('#score').textContent=`${student}: ${score}/10. ${score>=8?'Корекція успішна: алгоритми відновлено.':score>=6?'Є прогрес, але повторіть станції з помилками.':'Поверніться до станцій A–D і пройдіть їх ще раз.'}`});