const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let equal=false,reverse=false;
$$('[data-model]').forEach(b=>b.onclick=()=>{if(b.dataset.model==='equal'){equal=!equal;reverse=false}else{reverse=!reverse;equal=false}const a=equal?1013:reverse?1001:1022,c=equal?1013:reverse?1024:1004;$('#pA').textContent=a+' гПа';$('#pB').textContent=c+' гПа';$('#flowArrow').textContent=a===c?'↔':a>c?'→':'←';$('#pressureOut').textContent=a===c?'За відсутності різниці тиску модель не дає спрямованого потоку.':a>c?'Повітря рухається від вищого тиску А до нижчого Б.':'Тепер напрям змінився: від вищого тиску Б до нижчого А.'});
$$('[data-dir]').forEach(b=>b.onclick=()=>{const ok=b.dataset.dir==='right';$$('[data-dir]').forEach(x=>x.classList.remove('ok','no'));b.classList.add(ok?'ok':'no');$('#dirOut').className='feedback '+(ok?'good':'bad');$('#dirOut').textContent=ok?'Так. Назва вітру вказує, звідки він приходить.':'Ні. У метеорології напрям називають за стороною, звідки дме вітер.'});
const bf=[['Дим піднімається майже вертикально.','< 1 м/с','Штиль або майже штиль.'],['Листя і тонкі гілочки постійно рухаються.','≈ 3–5 м/с','Слабкий / помірний вітер.'],['Підіймається пил, рухаються тонкі гілки.','≈ 6–8 м/с','Помірний вітер.'],['Рухаються великі гілки, важко користуватися парасолею.','≈ 11–14 м/с','Сильний вітер.'],['Гойдаються цілі дерева, йти проти вітру важко.','≈ 17–21 м/с','Дуже сильний вітер / штормовий рівень.']];
$('#beaufortRange').oninput=e=>{const x=bf[+e.target.value];$('#beaufortScenario').textContent=x[0];$('#beaufortValue').textContent=x[1];$('#beaufortHint').textContent=x[2]};
const vals=[2,1,2,1,2,1,5,2],labs=['Пн','ПнСх','Сх','ПдСх','Пд','ПдЗх','Зх','ПнЗх'];
function drawRose(){const c=$('#roseCanvas'),x=c.getContext('2d'),cx=260,cy=260,max=5,R=200;x.clearRect(0,0,520,520);x.strokeStyle='#d8e8f0';x.fillStyle='#60798a';x.font='14px system-ui';for(let r=1;r<=5;r++){x.beginPath();x.arc(cx,cy,R*r/max,0,Math.PI*2);x.stroke()}for(let i=0;i<8;i++){const a=-Math.PI/2+i*Math.PI/4,rr=R*vals[i]/max;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.stroke();x.fillText(labs[i],cx+Math.cos(a)*(R+24)-10,cy+Math.sin(a)*(R+24)+5);x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a-Math.PI/18)*rr,cy+Math.sin(a-Math.PI/18)*rr);x.arc(cx,cy,rr,a-Math.PI/18,a+Math.PI/18);x.closePath();x.fillStyle='rgba(15,126,155,.58)';x.fill();x.fillStyle='#60798a'}$('#dominant').textContent='Переважає західний вітер: 5 із 16 днів'}
$('#drawRose').onclick=drawRose;drawRose();
$('#roseCheck').onclick=()=>{const t=$('#roseText').value.toLowerCase(),ok=t.includes('зах')&&t.includes('5');$('#roseOut').className='feedback '+(ok?'good':'bad');$('#roseOut').textContent=ok?'Висновок містить і напрям, і числовий доказ. Додайте, що довший промінь означає більшу повторюваність.':'Потрібно назвати західний напрям і вказати доказ: 5 днів із 16.'};
$$('[data-place]').forEach(b=>b.onclick=()=>{const ok=b.dataset.place==='good';$$('[data-place]').forEach(x=>x.classList.remove('ok','no'));b.classList.add(ok?'ok':'no');$('#factoryOut').className='feedback '+(ok?'good':'bad');$('#factoryOut').textContent=ok?'Логічно: західний вітер переносить повітря із заходу на схід, тому джерело східніше міста менше спрямовує шлейф через забудову. Реальне проєктування потребує значно більше даних.':'За західного вітру повітря рухається із заходу на схід. Перевірте, чи не опиниться місто під шлейфом.'});
$('#factoryCheck').onclick=()=>{const t=$('#factoryCER').value.toLowerCase(),ok=t.includes('зах')&&t.includes('схід')&&(t.includes('роза')||t.includes('5'));$('#factoryProof').className='feedback '+(ok?'good':'bad');$('#factoryProof').textContent=ok?'Є причинний ланцюг: повторюваність → напрям перенесення → вибір підвітряного боку. Важливо: для реального підприємства потрібні санітарні норми, рельєф і багаторічні метеодані.':'Додайте доказ із рози вітрів і чітко поясніть напрям перенесення із заходу на схід.'};
$('#cerBtn').onclick=()=>{const t=($('#cerC').value+' '+$('#cerE').value+' '+$('#cerR').value).toLowerCase(),ok=t.length>80&&(t.includes('тиск')||t.includes('вищ'))&&(t.includes('ниж'));$('#cerOut').className='feedback '+(ok?'good':'bad');$('#cerOut').textContent=ok?'CER має потрібний причинний зв’язок. Перевірте, чи ваш доказ конкретний: число, спостереження або результат моделі.':'Потрібні три частини: теза, конкретний доказ і пояснення через рух від вищого тиску до нижчого.'};
const Q=[
['Вітер — це…',['вертикальний рух води','горизонтальний рух повітря','рух хмар без переміщення повітря'],1],
['У спрощеній моделі повітря рухається…',['від нижчого тиску до вищого','від вищого тиску до нижчого','лише з півночі на південь'],1],
['Північний вітер дме…',['з півночі на південь','з півдня на північ','зі сходу на захід'],0],
['Прилад для вимірювання швидкості вітру…',['барометр','анемометр','гігрометр'],1],
['Флюгер насамперед показує…',['тиск','напрям вітру','вологість'],1],
['Роза вітрів показує…',['річну температуру','повторюваність напрямів вітру','висоту хмар'],1],
['У нашому наборі спостережень переважав вітер…',['західний','східний','південний'],0],
['Денний бриз на узбережжі зазвичай дме…',['із суходолу на воду','з води на суходіл','лише вздовж берега'],1],
['Якщо великі гілки сильно рухаються, вітер імовірно…',['сильніший, ніж коли ледве рухається листя','слабший','обов’язково штиль'],0],
['Чому для підприємства важлива багаторічна роза вітрів?',['бо один момент не характеризує переважний перенос','бо вітер завжди однаковий','бо напрям вітру не впливає на перенос'],0]
];
function renderQuiz(){const f=$('#quiz');f.innerHTML=Q.map((q,i)=>`<div class="q"><h3>${i+1}. ${q[0]}</h3>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('')+'<button class="btn" type="submit">Завершити тест</button>';}
renderQuiz();
$('#unlock').onclick=()=>{const ok=$('#surname').value.trim()&&$('#name').value.trim()&&$('#klass').value.trim();$('#lockMsg').className='feedback '+(ok?'good':'bad');$('#lockMsg').textContent=ok?'Тест відкрито. Успіхів!':'Заповніть усі три поля: прізвище, ім’я та клас.';if(ok)$('#quiz').classList.remove('hidden')};
$('#quiz').onsubmit=e=>{e.preventDefault();let s=0;Q.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q[2])s++});$('#result').classList.remove('hidden');$('#result').innerHTML=`${$('#surname').value} ${$('#name').value}, ${$('#klass').value}: <b>${s}/10</b>. ${s>=8?'Тему засвоєно добре.':s>=6?'Повторіть напрям вітру, розу вітрів і причину його виникнення.':'Поверніться до моделей тиску, напряму та практичної роботи з розою вітрів.'}`;$('#result').scrollIntoView({behavior:'smooth'})};