const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$$('.choices button').forEach(b=>b.addEventListener('click',()=>{const f=b.closest('section').querySelector('.feedback');const ok=b.dataset.answer==='right';f.className='feedback '+(ok?'ok':'bad');f.innerHTML=ok?'✅ Так. Висновок спирається на склад і будову, а не лише на зовнішній вигляд.':'❌ Спробуйте ще раз: твердість або колір самі по собі не роблять речовину мінералом.';}));
const picked={mineral:[],rock:[]};$$('#sorter button').forEach(b=>b.onclick=()=>{const k=b.dataset.kind;const name=b.textContent;if(picked[k].includes(name))picked[k]=picked[k].filter(x=>x!==name);else picked[k].push(name);$('#mineralZone').textContent=picked.mineral.join(', ')||'—';$('#rockZone').textContent=picked.rock.join(', ')||'—';b.classList.toggle('selected')});$('#sortCheck').onclick=()=>{const ok=picked.mineral.length===3&&picked.rock.length===3;$('#sortFeedback').className='feedback '+(ok?'ok':'bad');$('#sortFeedback').textContent=ok?'✅ Класифікація повна: мінерали — кварц, кальцит, галіт; породи — граніт, базальт, вапняк.':'Перевірте, чи всі 6 зразків розподілені. Орієнтир: порода може складатися з одного або кількох мінералів.'};
$$('.process-grid button').forEach(b=>b.onclick=()=>$('#processFeedback').innerHTML=b.dataset.text);
$('#crystalCheck').onclick=()=>{const ok=$('#crystalQ').value==='deep';$('#crystalFeedback').className='feedback '+(ok?'ok':'bad');$('#crystalFeedback').innerHTML=ok?'✅ Повільне охолодження дає кристалам більше часу для росту — це сильний доказ глибинного застигання.':'Не зовсім. Великі кристали найкраще узгоджуються з повільним охолодженням магми в надрах.'};
$$('[data-clay]').forEach(b=>b.onclick=()=>{const k=b.dataset.clay;const sample=$('#claySample'),f=$('#clayFeedback');if(k==='iron'){sample.style.background='#b95f42';sample.style.color='white';f.textContent='Оксиди та гідроксиди заліза часто дають червоні, бурі й жовті відтінки.'}if(k==='organic'){sample.style.background='#55524f';sample.style.color='white';f.textContent='Органічна речовина та відновні умови можуть робити глину сірою або темною.'}if(k==='clean'){sample.style.background='#eee8dc';sample.style.color='#17324a';f.textContent='За малої кількості фарбувальних домішок глина може бути світлою, кремовою або майже білою.'}});
const plan=$('#plan');$('#shufflePlan').onclick=()=>{[...plan.children].sort(()=>Math.random()-.5).forEach(x=>plan.appendChild(x));$('#planFeedback').textContent='Порядок перемішано. Перетягуйте кроки пальцем або мишкою не потрібно — просто натискайте їх у правильній послідовності.';let seq=[];[...plan.children].forEach(li=>{li.onclick=()=>{if(li.dataset.chosen)return;li.dataset.chosen='1';li.style.outline='3px solid #8ed8c8';seq.push(li.dataset.step);li.dataset.order=seq.length;li.insertAdjacentHTML('beforeend',` <b>(${seq.length})</b>`);plan.dataset.seq=seq.join(',')}})};$('#checkPlan').onclick=()=>{let seq=(plan.dataset.seq||'').split(',').filter(Boolean);if(!seq.length)seq=[...plan.children].map(x=>x.dataset.step);const ok=seq.join(',')==='1,2,3,4,5';$('#planFeedback').className='feedback '+(ok?'ok':'bad');$('#planFeedback').textContent=ok?'✅ Логіка дослідження правильна: спостереження → прості тести → порівняння з джерелом → доказовий висновок.':'Логіка порушена. Спочатку безпечні спостереження, потім тести, потім перевірка за визначником і висновок.'};
const uses={quartz:'Скло виготовляють переважно із кварцового піску — джерела SiO₂.',clay:'Цегла й кераміка базуються на глинистій сировині, яку формують та випалюють.',limestone:'Вапняк — одна з головних сировин для цементу та вапна.',gypsum:'Гіпс — основа багатьох штукатурок і гіпсокартонних плит.',copper:'Мідні руди дають метал для електропроводки завдяки високій електропровідності міді.',granite:'Граніт використовують як міцний облицювальний і будівельний камінь.'};$$('[data-use]').forEach(b=>b.onclick=()=>$('#houseFeedback').textContent=uses[b.dataset.use]);
$$('.check[data-target]').forEach(b=>b.onclick=()=>$('#'+b.dataset.target).classList.toggle('show'));
const qs=[
['Що точніше описує мінерал?',['Природна речовина з характерним складом і внутрішньою будовою','Будь-який твердий камінь','Суміш тільки трьох речовин'],0],
['Що є гірською породою?',['Кварц','Граніт','Галіт'],1],
['Чому в граніті часто великі кристали?',['Він застигає дуже швидко','Магма повільно охолоджується в надрах','Його розчиняє вода'],1],
['Базальт найчастіше утворюється...',['зі швидко застиглої лави','з випарування морської води','з рослинних решток'],0],
['Який процес безпосередньо утворює кам’яну сіль у випарних басейнах?',['Кристалізація під час випаровування','Горіння','Плавлення льоду'],0],
['Що найкраще пояснює червону глину?',['Домішки оксидів заліза','Велика кількість льоду','Відсутність будь-яких домішок'],0],
['Вапняк належить переважно до...',['магматичних порід','осадових порід','металів'],1],
['Який доказ найкорисніший для визначення породи?',['Лише колір','Сукупність: зернистість, склад, шаруватість, тести','Лише маса зразка'],1],
['Що правильно про граніт і кварц?',['Граніт — мінерал кварц','Кварц може бути одним із мінералів граніту','Кварц утворюється тільки в морі'],1],
['Навіщо в дослідженні посилатися на надійний визначник?',['Щоб замінити спостереження','Щоб перевірити гіпотезу за описаними ознаками','Щоб не записувати докази'],1]
];
$('#quizBody').innerHTML=qs.map((q,i)=>`<div class="quiz-q"><b>${i+1}. ${q[0]}</b>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('');
$('#unlock').onclick=()=>{const ok=$('#surname').value.trim().length>1&&$('#name').value.trim().length>1&&$('#klass').value;if(ok){$('#quiz').classList.add('open');$('#gateFeedback').className='feedback ok';$('#gateFeedback').textContent='✅ Дані введено. Тест відкрито.'}else{$('#gateFeedback').className='feedback bad';$('#gateFeedback').textContent='Введіть прізвище, ім’я та клас.'}};
$('#quiz').onsubmit=e=>{e.preventDefault();let s=0;qs.forEach((q,i)=>{const x=document.querySelector(`input[name=q${i}]:checked`);if(x&&+x.value===q[2])s++});$('#score').innerHTML=`${$('#surname').value} ${$('#name').value}, ${$('#klass').value}: <strong>${s}/10</strong>${s>=8?' — матеріал засвоєно.':s>=6?' — повторіть склад і походження порід.':' — поверніться до лабораторних блоків 02–07.'}`;};