
const score={warm1:0,warm2:0,africa:0,australia:0,choice:0};
function val(id){return Number(document.getElementById(id).value)}
function inRange(x,a,b){return Number.isFinite(x)&&x>=a&&x<=b}
function fb(id,msg,ok){const e=document.getElementById(id);e.textContent=msg;e.className='feedback show '+(ok?'ok':'bad')}
function updateScore(){const s=Object.values(score).reduce((a,b)=>a+b,0);document.getElementById('autoScore').textContent=s;return s}
function markDot(id,on){document.getElementById(id).classList.toggle('done',on)}
function warm(btn,n,ok){document.querySelectorAll(`[data-warm="${n}"]`).forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');score['warm'+n]=ok?1:0;fb('warmFb',ok?'Так. Логіка вибрана правильно.':'Ні. Поверніться до алгоритму вище й подивіться, яка координата змінюється.',ok);updateScore()}
function showHint(id){document.getElementById(id).classList.add('show')}
function checkAfrica(){const n=val('afN'),s=val('afS'),d=val('afDeg'),km=val('afKm');let p=0;const coords=inRange(n,34,40)&&inRange(s,32,38);const deg=inRange(d,68,76);const dist=inRange(km,7400,8500);if(coords)p++;if(deg)p++;if(dist)p++;score.africa=p;markDot('dotAfrica',p===3);const parts=[coords?'координати ✓':'перевірте крайні широти',deg?'Δφ ✓':'перевірте додавання широт',dist?'км ✓':'перевірте Δφ × 111'];fb('africaFb',`${p}/3. ${parts.join(' • ')}`,p===3);updateScore()}
function checkAustralia(){const w=val('auW'),e=val('auE'),d=val('auDeg'),km=val('auKm');let p=0;const coords=inRange(w,112,119)&&inRange(e,149,155);const deg=inRange(d,33,43);const dist=inRange(km,3200,4150);if(coords)p++;if(deg)p++;if(dist)p++;score.australia=p;markDot('dotAustralia',p===3);const parts=[coords?'довготи ✓':'перевірте перетини 30° пд. ш.',deg?'Δλ ✓':'перевірте різницю довгот',dist?'км ✓':'на 30° використайте 96,5 км за 1°'];fb('australiaFb',`${p}/3. ${parts.join(' • ')}`,p===3);updateScore()}
function choiceModeChanged(){const mode=document.getElementById('choiceMode').value;document.getElementById('choiceText').innerHTML=mode==='sa'?'<b>Південна Америка:</b> оцініть широти крайніх північної та південної точок, знайдіть Δφ та помножте на 111 км.':'<b>Африка по 10° пн. ш.:</b> оцініть західну й східну довготи перетину паралелі з материком, знайдіть Δλ і помножте приблизно на 109,6 км.';score.choice=0;markDot('dotChoice',false);updateScore()}
function checkChoice(){const mode=document.getElementById('choiceMode').value,d=val('chDeg'),km=val('chKm'),m=document.getElementById('chMethod').value.trim();let goodD=false,goodK=false;if(mode==='sa'){goodD=inRange(d,62,71);goodK=inRange(km,6800,7900)}else{goodD=inRange(d,60,71);goodK=inRange(km,6500,7900)}const method=m.length>=18;let p=(goodD&&goodK?1:0)+(method?1:0);score.choice=p;markDot('dotChoice',p===2);fb('choiceFb',`${p}/2. ${goodD&&goodK?'Розрахунок у правдоподібному діапазоні.':'Перевірте градуси або множник.'} ${method?'Спосіб пояснено.':'Додайте коротке пояснення способу.'}`,p===2);updateScore()}
function checkErrors(){const selected=[...document.querySelectorAll('.err:checked')].map(x=>x.value);const bad=selected.filter(x=>x.startsWith('fake'));const good=selected.filter(x=>!x.startsWith('fake'));const ok=good.length>=3&&bad.length===0;fb('errorFb',ok?'Добре: ви назвали реальні джерела похибки й не обрали вигадані.':'Потрібно обрати щонайменше три реальні причини й жодної вигаданої.',ok)}
function buildReport(){const name=document.getElementById('student').value.trim(),cl=document.getElementById('studentClass').value.trim(),dt=document.getElementById('workDate').value,con=document.getElementById('conclusion').value.trim(),s=updateScore();const box=document.getElementById('resultCard');box.style.display='block';box.innerHTML=`<h3>Картка практичної роботи</h3><p><b>Учень/учениця:</b> ${name||'—'} &nbsp; <b>Клас:</b> ${cl||'—'} &nbsp; <b>Дата:</b> ${dt||new Date().toLocaleDateString('uk-UA')}</p><p><b>Автоматична частина:</b> ${s}/10. <b>Висновок:</b> 0–2 бали після перевірки вчителем. <b>Максимум:</b> 12.</p><p><b>Висновок учня:</b> ${con?con.replace(/</g,'&lt;'):'не заповнено'}</p><p class="subtle">Зробіть скриншот цієї картки або надрукуйте сторінку.</p>`}
function validFullName(v){const p=v.trim().replace(/\s+/g,' ').split(' ');return p.length>=2&&p.every(x=>/^[А-ЯІЇЄҐа-яіїєґ'’\-]+$/.test(x))}
function unlockQuiz(){const n=document.getElementById('quizName'),c=document.getElementById('quizClass');if(!n.value&&document.getElementById('student').value)n.value=document.getElementById('student').value;if(!c.value&&document.getElementById('studentClass').value)c.value=document.getElementById('studentClass').value;if(!validFullName(n.value)||!c.value.trim()){fb('quizGate','Введіть ім’я та прізвище і клас.',false);return}document.getElementById('quiz').classList.add('open');fb('quizGate','Тест відкрито. Правильні відповіді з’являться тільки після завершення.',true)}
function gradeQuiz(){let s=0;document.querySelectorAll('.q').forEach((q,i)=>{const a=q.querySelector(`input[name="q${i+1}"]:checked`);if(a&&a.value===q.dataset.a)s++});const name=document.getElementById('quizName').value.trim(),cl=document.getElementById('quizClass').value.trim();document.getElementById('quizResult').innerHTML=`<div class="resultcard"><b>${name}, ${cl}</b><br>Результат: <b>${s}/10</b> (${s*10}%). ${s>=8?'Матеріал засвоєно впевнено.':s>=5?'Є основа, але алгоритм варто повторити.':'Поверніться до алгоритму й виконайте два приклади ще раз.'}<br><span class="subtle">Зробіть скриншот результату.</span></div>`}
function saveAll(){const data={};document.querySelectorAll('[data-save]').forEach(el=>{if(el.type==='checkbox')data[el.id||el.value]=el.checked;else data[el.id]=el.value});localStorage.setItem('geo7_lesson8_practical',JSON.stringify(data))}
function loadAll(){try{const data=JSON.parse(localStorage.getItem('geo7_lesson8_practical')||'{}');document.querySelectorAll('[data-save]').forEach(el=>{const k=el.id||el.value;if(k in data){if(el.type==='checkbox')el.checked=!!data[k];else el.value=data[k]}})}catch(e){}choiceModeChanged()}
document.addEventListener('input',e=>{if(e.target.matches('[data-save]'))saveAll()});document.addEventListener('change',e=>{if(e.target.matches('[data-save]'))saveAll()});
window.addEventListener('DOMContentLoaded',()=>{if(!document.getElementById('workDate').value)document.getElementById('workDate').value=new Date().toISOString().slice(0,10);loadAll()});
